// -------------------------------------------------------------
// 
// File Name: C:\Users\Carlos Cajas\Desktop\DSP\nuevo_chale\FDHT_N\RADIX22FFT_SDF2_4_block.v
// Created: 2020-12-08 16:13:17
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_4_block
// Source Path: FDHT_N/FDHT/DFT-2/RADIX22FFT_SDF2_4
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_4_block
          (clk,
           reset_x,
           enb,
           dout_3_1_re,
           dout_3_1_im,
           dout_3_1_vld,
           rd_4_Addr,
           rd_4_Enb,
           proc_4_enb,
           multiply_4_J,
           softReset,
           dout_4_1_re,
           dout_4_1_im,
           dout_4_1_vld,
           dinXTwdl_4_1_vld);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [40:0] dout_3_1_re;  // sfix41_En28
  input   signed [40:0] dout_3_1_im;  // sfix41_En28
  input   dout_3_1_vld;
  input   [1:0] rd_4_Addr;  // ufix2
  input   rd_4_Enb;
  input   proc_4_enb;
  input   multiply_4_J;
  input   softReset;
  output  signed [40:0] dout_4_1_re;  // sfix41_En28
  output  signed [40:0] dout_4_1_im;  // sfix41_En28
  output  dout_4_1_vld;
  output  dinXTwdl_4_1_vld;

  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [40:0] wrData_im;  // sfix41_En28
  wire [1:0] wrAddr;  // ufix2
  wire wrEnb;
  wire signed [40:0] x_im;  // sfix41_En28
  reg signed [40:0] x_im_dly;  // sfix41_En28
  wire signed [40:0] wrData_re;  // sfix41_En28
  wire signed [40:0] x_re;  // sfix41_En28
  reg signed [40:0] x_re_dly;  // sfix41_En28
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [41:0] Radix22ButterflyG2_btf1_re_reg;  // sfix42
  reg signed [41:0] Radix22ButterflyG2_btf1_im_reg;  // sfix42
  reg signed [41:0] Radix22ButterflyG2_btf2_re_reg;  // sfix42
  reg signed [41:0] Radix22ButterflyG2_btf2_im_reg;  // sfix42
  reg signed [40:0] Radix22ButterflyG2_din_re_dly;  // sfix41
  reg signed [40:0] Radix22ButterflyG2_din_im_dly;  // sfix41
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [40:0] Radix22ButterflyG2_x_re_dly;  // sfix41
  reg signed [40:0] Radix22ButterflyG2_x_im_dly;  // sfix41
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix41
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix41
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix41
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix41
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [41:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix42_En28
  reg signed [40:0] Radix22ButterflyG2_din_re_dly_next;  // sfix41_En28
  reg signed [40:0] Radix22ButterflyG2_din_im_dly_next;  // sfix41_En28
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [40:0] Radix22ButterflyG2_x_re_dly_next;  // sfix41_En28
  reg signed [40:0] Radix22ButterflyG2_x_im_dly_next;  // sfix41_En28
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix41_En28
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix41_En28
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix41_En28
  reg signed [40:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix41_En28
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [40:0] xf_re;  // sfix41_En28
  reg signed [40:0] xf_im;  // sfix41_En28
  reg  xf_vld;
  reg signed [40:0] dinf_re;  // sfix41_En28
  reg signed [40:0] dinf_im;  // sfix41_En28
  reg  dinf_vld;
  reg signed [40:0] btf1_re;  // sfix41_En28
  reg signed [40:0] btf1_im;  // sfix41_En28
  reg signed [40:0] btf2_re;  // sfix41_En28
  reg signed [40:0] btf2_im;  // sfix41_En28
  reg  btfout_vld;
  reg signed [41:0] Radix22ButterflyG2_add_cast;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_0;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_1;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_2;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_0;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_1;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_2;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_3;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_4;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_5;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_add_cast_6;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_3;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_4;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_5;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sub_cast_6;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sra_temp;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sra_temp_0;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sra_temp_1;  // sfix42_En28
  reg signed [41:0] Radix22ButterflyG2_sra_temp_2;  // sfix42_En28


  assign btfin_vld = dout_3_1_vld & proc_4_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_3_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset_x == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_4_Enb;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset_x == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(2),
                              .DataWidth(41)
                              )
                            u_dataMEM_im_0_4 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_4_Addr),
                                              .rd_dout(x_im)
                                              );

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset_x == 1'b1) begin
        x_im_dly <= 41'sh00000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(2),
                              .DataWidth(41)
                              )
                            u_dataMEM_re_0_4 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_4_Addr),
                                              .rd_dout(x_re)
                                              );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset_x == 1'b1) begin
        x_re_dly <= 41'sh00000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset_x == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 42'sh00000000000;
        Radix22ButterflyG2_btf1_im_reg <= 42'sh00000000000;
        Radix22ButterflyG2_btf2_re_reg <= 42'sh00000000000;
        Radix22ButterflyG2_btf2_im_reg <= 42'sh00000000000;
        Radix22ButterflyG2_din_re_dly <= 41'sh00000000000;
        Radix22ButterflyG2_din_im_dly <= 41'sh00000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 41'sh00000000000;
        Radix22ButterflyG2_x_im_dly <= 41'sh00000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 41'sh00000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 41'sh00000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 41'sh00000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 41'sh00000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_vld_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_vld_dly, Radix22ButterflyG2_dinXTwdl_re_dly1,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_dinXTwdl_im_dly2, Radix22ButterflyG2_multiply_J_dly1,
       dout_3_1_re, dout_3_1_im, dinVld, dout_3_1_re, dout_3_1_im, btfin_vld,
       x_re_dly, x_im_dly, x_vld_dly, multiply_4_J) begin
    Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_btf1_re_reg;
    Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_btf1_im_reg;
    Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_btf2_re_reg;
    Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_btf2_im_reg;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = dout_3_1_re;
    Radix22ButterflyG2_din_im_dly_next = dout_3_1_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[40], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[40], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[40], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[40], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[40], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[40], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[40], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[40], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[40], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[40], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[40], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[40], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[40], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[40], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[40], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[40], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = dout_3_1_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = dout_3_1_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_4_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    Radix22ButterflyG2_sra_temp = Radix22ButterflyG2_btf1_re_reg >>> 8'd1;
    btf1_re = Radix22ButterflyG2_sra_temp[40:0];
    Radix22ButterflyG2_sra_temp_0 = Radix22ButterflyG2_btf1_im_reg >>> 8'd1;
    btf1_im = Radix22ButterflyG2_sra_temp_0[40:0];
    Radix22ButterflyG2_sra_temp_1 = Radix22ButterflyG2_btf2_re_reg >>> 8'd1;
    btf2_re = Radix22ButterflyG2_sra_temp_1[40:0];
    Radix22ButterflyG2_sra_temp_2 = Radix22ButterflyG2_btf2_im_reg >>> 8'd1;
    btf2_im = Radix22ButterflyG2_sra_temp_2[40:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator4_block u_SDFCOMMUTATOR_4 (.clk(clk),
                                          .reset_x(reset_x),
                                          .enb(enb),
                                          .dout_3_1_vld(dout_3_1_vld),
                                          .xf_re(xf_re),  // sfix41_En28
                                          .xf_im(xf_im),  // sfix41_En28
                                          .xf_vld(xf_vld),
                                          .dinf_re(dinf_re),  // sfix41_En28
                                          .dinf_im(dinf_im),  // sfix41_En28
                                          .dinf_vld(dinf_vld),
                                          .btf1_re(btf1_re),  // sfix41_En28
                                          .btf1_im(btf1_im),  // sfix41_En28
                                          .btf2_re(btf2_re),  // sfix41_En28
                                          .btf2_im(btf2_im),  // sfix41_En28
                                          .btfout_vld(btfout_vld),
                                          .softReset(softReset),
                                          .wrData_re(wrData_re),  // sfix41_En28
                                          .wrData_im(wrData_im),  // sfix41_En28
                                          .wrAddr(wrAddr),  // ufix2
                                          .wrEnb(wrEnb),
                                          .dout_4_1_re(dout_4_1_re),  // sfix41_En28
                                          .dout_4_1_im(dout_4_1_im),  // sfix41_En28
                                          .dout_4_1_vld(dout_4_1_vld)
                                          );

  assign dinXTwdl_4_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_4_block

