// -------------------------------------------------------------
// 
// File Name: C:\Users\Carlos Cajas\Desktop\DSP\nuevo_chale\FDHT_N\swapping2.v
// Created: 2020-12-08 16:13:16
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: swapping2
// Source Path: FDHT_N/FDHT/swapping2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module swapping2
          (In1_re,
           In1_im,
           Out1_re,
           Out1_im);


  input   signed [40:0] In1_re;  // sfix41_En28
  input   signed [40:0] In1_im;  // sfix41_En28
  output  signed [40:0] Out1_re;  // sfix41_En28
  output  signed [40:0] Out1_im;  // sfix41_En28



  assign Out1_re = In1_im;

  assign Out1_im = In1_re;

endmodule  // swapping2

