// -------------------------------------------------------------
// 
// File Name: C:\Users\Carlos Cajas\Desktop\henkindama2\newhope_cambios\DFT_2.v
// Created: 2020-12-20 13:10:05
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DFT_2
// Source Path: newhope_cambios/FDHT/DFT_2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DFT_2
          (clk,
           reset_x,
           enb,
           In1_re,
           In1_im,
           In2_re,
           In2_im,
           In3_re,
           In3_im,
           In4_re,
           In4_im,
           In5_re,
           In5_im,
           In6_re,
           In6_im,
           In7_re,
           In7_im,
           In8_re,
           In8_im,
           In9_re,
           In9_im,
           In10_re,
           In10_im,
           In11_re,
           In11_im,
           In12_re,
           In12_im,
           In13_re,
           In13_im,
           In14_re,
           In14_im,
           In15_re,
           In15_im,
           In16_re,
           In16_im,
           In17_re,
           In17_im,
           In18_re,
           In18_im,
           In19_re,
           In19_im,
           In20_re,
           In20_im,
           In21_re,
           In21_im,
           In22_re,
           In22_im,
           In23_re,
           In23_im,
           In24_re,
           In24_im,
           In25_re,
           In25_im,
           x10_1_4_re,
           x10_1_4_im,
           In27,
           In28,
           In29,
           Out1_re,
           Out1_im,
           Out2_re,
           Out2_im,
           Out3_re,
           Out3_im,
           Out4_re,
           Out4_im,
           Out5_re,
           Out5_im,
           Out6_re,
           Out6_im,
           Out7_re,
           Out7_im,
           Out8_re,
           Out8_im,
           Out9_re,
           Out9_im,
           Out10_re,
           Out10_im);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [36:0] In1_re;  // sfix37_En22
  input   signed [36:0] In1_im;  // sfix37_En22
  input   signed [36:0] In2_re;  // sfix37_En22
  input   signed [36:0] In2_im;  // sfix37_En22
  input   signed [36:0] In3_re;  // sfix37_En22
  input   signed [36:0] In3_im;  // sfix37_En22
  input   signed [36:0] In4_re;  // sfix37_En22
  input   signed [36:0] In4_im;  // sfix37_En22
  input   signed [36:0] In5_re;  // sfix37_En22
  input   signed [36:0] In5_im;  // sfix37_En22
  input   signed [36:0] In6_re;  // sfix37_En22
  input   signed [36:0] In6_im;  // sfix37_En22
  input   signed [36:0] In7_re;  // sfix37_En22
  input   signed [36:0] In7_im;  // sfix37_En22
  input   signed [36:0] In8_re;  // sfix37_En22
  input   signed [36:0] In8_im;  // sfix37_En22
  input   signed [36:0] In9_re;  // sfix37_En22
  input   signed [36:0] In9_im;  // sfix37_En22
  input   signed [36:0] In10_re;  // sfix37_En22
  input   signed [36:0] In10_im;  // sfix37_En22
  input   signed [36:0] In11_re;  // sfix37_En22
  input   signed [36:0] In11_im;  // sfix37_En22
  input   signed [36:0] In12_re;  // sfix37_En22
  input   signed [36:0] In12_im;  // sfix37_En22
  input   signed [36:0] In13_re;  // sfix37_En22
  input   signed [36:0] In13_im;  // sfix37_En22
  input   signed [36:0] In14_re;  // sfix37_En22
  input   signed [36:0] In14_im;  // sfix37_En22
  input   signed [36:0] In15_re;  // sfix37_En22
  input   signed [36:0] In15_im;  // sfix37_En22
  input   signed [36:0] In16_re;  // sfix37_En22
  input   signed [36:0] In16_im;  // sfix37_En22
  input   signed [36:0] In17_re;  // sfix37_En22
  input   signed [36:0] In17_im;  // sfix37_En22
  input   signed [36:0] In18_re;  // sfix37_En22
  input   signed [36:0] In18_im;  // sfix37_En22
  input   signed [36:0] In19_re;  // sfix37_En22
  input   signed [36:0] In19_im;  // sfix37_En22
  input   signed [36:0] In20_re;  // sfix37_En22
  input   signed [36:0] In20_im;  // sfix37_En22
  input   signed [36:0] In21_re;  // sfix37_En22
  input   signed [36:0] In21_im;  // sfix37_En22
  input   signed [36:0] In22_re;  // sfix37_En22
  input   signed [36:0] In22_im;  // sfix37_En22
  input   signed [36:0] In23_re;  // sfix37_En22
  input   signed [36:0] In23_im;  // sfix37_En22
  input   signed [36:0] In24_re;  // sfix37_En22
  input   signed [36:0] In24_im;  // sfix37_En22
  input   signed [36:0] In25_re;  // sfix37_En22
  input   signed [36:0] In25_im;  // sfix37_En22
  input   x10_1_4_re;  // ufix1
  input   x10_1_4_im;  // ufix1
  input   [7:0] In27;  // uint8
  input   [7:0] In28;  // uint8
  input   [7:0] In29;  // uint8
  output  signed [36:0] Out1_re;  // sfix37_En22
  output  signed [36:0] Out1_im;  // sfix37_En22
  output  signed [36:0] Out2_re;  // sfix37_En22
  output  signed [36:0] Out2_im;  // sfix37_En22
  output  signed [36:0] Out3_re;  // sfix37_En22
  output  signed [36:0] Out3_im;  // sfix37_En22
  output  signed [36:0] Out4_re;  // sfix37_En22
  output  signed [36:0] Out4_im;  // sfix37_En22
  output  signed [36:0] Out5_re;  // sfix37_En22
  output  signed [36:0] Out5_im;  // sfix37_En22
  output  signed [36:0] Out6_re;  // sfix37_En22
  output  signed [36:0] Out6_im;  // sfix37_En22
  output  signed [36:0] Out7_re;  // sfix37_En22
  output  signed [36:0] Out7_im;  // sfix37_En22
  output  signed [36:0] Out8_re;  // sfix37_En22
  output  signed [36:0] Out8_im;  // sfix37_En22
  output  signed [36:0] Out9_re;  // sfix37_En22
  output  signed [36:0] Out9_im;  // sfix37_En22
  output  signed [36:0] Out10_re;  // sfix37_En22
  output  signed [36:0] Out10_im;  // sfix37_En22


  wire signed [36:0] save_DFT50_swapping_values_out1_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out1_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out2_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out2_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out3_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out3_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out4_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out4_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out5_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out5_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out6_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out6_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out7_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out7_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out8_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out8_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out9_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out9_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out10_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out10_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out11_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out11_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out12_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out12_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out13_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out13_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out14_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out14_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out15_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out15_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out16_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out16_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out17_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out17_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out18_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out18_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out19_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out19_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out20_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out20_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out21_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out21_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out22_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out22_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out23_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out23_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out24_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out24_im;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out25_re;  // sfix37_En22
  wire signed [36:0] save_DFT50_swapping_values_out25_im;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out1_re;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out1_im;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out2_re;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out2_im;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out3_re;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out3_im;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out4_re;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out4_im;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out5_re;  // sfix37_En22
  wire signed [36:0] switching_DFT50_swapping_values_out5_im;  // sfix37_En22
  wire signed [36:0] Constant4_out1;  // sfix37_En22
  wire signed [36:0] Constant5_out1;  // sfix37_En22
  wire signed [36:0] Constant6_out1;  // sfix37_En22
  wire signed [36:0] Constant7_out1;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out1_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out1_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out2_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out2_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out3_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out3_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out4_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out4_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out5_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out5_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out6_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out6_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out7_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out7_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out8_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out8_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out9_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out9_im;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out10_re;  // sfix37_En22
  wire signed [36:0] DFT10_block_2_out10_im;  // sfix37_En22
  wire signed [36:0] W50_out1_re;  // sfix37_En22
  wire signed [36:0] W50_out1_im;  // sfix37_En22
  wire signed [36:0] W50_out2_re;  // sfix37_En22
  wire signed [36:0] W50_out2_im;  // sfix37_En22
  wire signed [36:0] W50_out3_re;  // sfix37_En22
  wire signed [36:0] W50_out3_im;  // sfix37_En22
  wire signed [36:0] W50_out4_re;  // sfix37_En22
  wire signed [36:0] W50_out4_im;  // sfix37_En22
  wire signed [36:0] W50_out5_re;  // sfix37_En22
  wire signed [36:0] W50_out5_im;  // sfix37_En22
  wire signed [36:0] W50_out6_re;  // sfix37_En22
  wire signed [36:0] W50_out6_im;  // sfix37_En22
  wire signed [36:0] W50_out7_re;  // sfix37_En22
  wire signed [36:0] W50_out7_im;  // sfix37_En22
  wire signed [36:0] W50_out8_re;  // sfix37_En22
  wire signed [36:0] W50_out8_im;  // sfix37_En22
  wire signed [36:0] W50_out9_re;  // sfix37_En22
  wire signed [36:0] W50_out9_im;  // sfix37_En22
  wire signed [36:0] W50_out10_re;  // sfix37_En22
  wire signed [36:0] W50_out10_im;  // sfix37_En22
  wire signed [36:0] save_G_values_out1;  // sfix37_En22
  wire signed [36:0] save_G_values_out2;  // sfix37_En22
  wire signed [36:0] save_G_values_out3;  // sfix37_En22
  wire signed [36:0] save_G_values_out4;  // sfix37_En22
  wire signed [36:0] save_G_values_out5;  // sfix37_En22
  wire signed [36:0] save_G_values_out6;  // sfix37_En22
  wire signed [36:0] save_G_values_out7;  // sfix37_En22
  wire signed [36:0] save_G_values_out8;  // sfix37_En22
  wire signed [36:0] save_G_values_out9;  // sfix37_En22
  wire signed [36:0] save_G_values_out10;  // sfix37_En22
  wire signed [36:0] save_G_values_out11;  // sfix37_En22
  wire signed [36:0] save_G_values_out12;  // sfix37_En22
  wire signed [36:0] save_G_values_out13;  // sfix37_En22
  wire signed [36:0] save_G_values_out14;  // sfix37_En22
  wire signed [36:0] save_G_values_out15;  // sfix37_En22
  wire signed [36:0] save_G_values_out16;  // sfix37_En22
  wire signed [36:0] save_G_values_out17;  // sfix37_En22
  wire signed [36:0] save_G_values_out18;  // sfix37_En22
  wire signed [36:0] save_G_values_out19;  // sfix37_En22
  wire signed [36:0] save_G_values_out20;  // sfix37_En22
  wire signed [36:0] save_G_values_out21;  // sfix37_En22
  wire signed [36:0] save_G_values_out22;  // sfix37_En22
  wire signed [36:0] save_G_values_out23;  // sfix37_En22
  wire signed [36:0] save_G_values_out24;  // sfix37_En22
  wire signed [36:0] save_G_values_out25;  // sfix37_En22
  wire signed [36:0] save_G_values_out26;  // sfix37_En22
  wire signed [36:0] save_G_values_out27;  // sfix37_En22
  wire signed [36:0] save_G_values_out28;  // sfix37_En22
  wire signed [36:0] save_G_values_out29;  // sfix37_En22
  wire signed [36:0] save_G_values_out30;  // sfix37_En22
  wire signed [36:0] save_G_values_out31;  // sfix37_En22
  wire signed [36:0] save_G_values_out32;  // sfix37_En22
  wire signed [36:0] save_G_values_out33;  // sfix37_En22
  wire signed [36:0] save_G_values_out34;  // sfix37_En22
  wire signed [36:0] save_G_values_out35;  // sfix37_En22
  wire signed [36:0] save_G_values_out36;  // sfix37_En22
  wire signed [36:0] save_G_values_out37;  // sfix37_En22
  wire signed [36:0] save_G_values_out38;  // sfix37_En22
  wire signed [36:0] save_G_values_out39;  // sfix37_En22
  wire signed [36:0] save_G_values_out40;  // sfix37_En22
  wire signed [36:0] save_G_values_out41;  // sfix37_En22
  wire signed [36:0] save_G_values_out42;  // sfix37_En22
  wire signed [36:0] save_G_values_out43;  // sfix37_En22
  wire signed [36:0] save_G_values_out44;  // sfix37_En22
  wire signed [36:0] save_G_values_out45;  // sfix37_En22
  wire signed [36:0] save_G_values_out46;  // sfix37_En22
  wire signed [36:0] save_G_values_out47;  // sfix37_En22
  wire signed [36:0] save_G_values_out48;  // sfix37_En22
  wire signed [36:0] save_G_values_out49;  // sfix37_En22
  wire signed [36:0] save_G_values_out50;  // sfix37_En22
  wire signed [36:0] save_G_values_out51;  // sfix37_En22
  wire signed [36:0] save_G_values_out52;  // sfix37_En22
  wire signed [36:0] save_G_values_out53;  // sfix37_En22
  wire signed [36:0] save_G_values_out54;  // sfix37_En22
  wire signed [36:0] save_G_values_out55;  // sfix37_En22
  wire signed [36:0] save_G_values_out56;  // sfix37_En22
  wire signed [36:0] save_G_values_out57;  // sfix37_En22
  wire signed [36:0] save_G_values_out58;  // sfix37_En22
  wire signed [36:0] save_G_values_out59;  // sfix37_En22
  wire signed [36:0] save_G_values_out60;  // sfix37_En22
  wire signed [36:0] save_G_values_out61;  // sfix37_En22
  wire signed [36:0] save_G_values_out62;  // sfix37_En22
  wire signed [36:0] save_G_values_out63;  // sfix37_En22
  wire signed [36:0] save_G_values_out64;  // sfix37_En22
  wire signed [36:0] save_G_values_out65;  // sfix37_En22
  wire signed [36:0] save_G_values_out66;  // sfix37_En22
  wire signed [36:0] save_G_values_out67;  // sfix37_En22
  wire signed [36:0] save_G_values_out68;  // sfix37_En22
  wire signed [36:0] save_G_values_out69;  // sfix37_En22
  wire signed [36:0] save_G_values_out70;  // sfix37_En22
  wire signed [36:0] save_G_values_out71;  // sfix37_En22
  wire signed [36:0] save_G_values_out72;  // sfix37_En22
  wire signed [36:0] save_G_values_out73;  // sfix37_En22
  wire signed [36:0] save_G_values_out74;  // sfix37_En22
  wire signed [36:0] save_G_values_out75;  // sfix37_En22
  wire signed [36:0] save_G_values_out76;  // sfix37_En22
  wire signed [36:0] save_G_values_out77;  // sfix37_En22
  wire signed [36:0] save_G_values_out78;  // sfix37_En22
  wire signed [36:0] save_G_values_out79;  // sfix37_En22
  wire signed [36:0] save_G_values_out80;  // sfix37_En22
  wire signed [36:0] save_G_values_out81;  // sfix37_En22
  wire signed [36:0] save_G_values_out82;  // sfix37_En22
  wire signed [36:0] save_G_values_out83;  // sfix37_En22
  wire signed [36:0] save_G_values_out84;  // sfix37_En22
  wire signed [36:0] save_G_values_out85;  // sfix37_En22
  wire signed [36:0] save_G_values_out86;  // sfix37_En22
  wire signed [36:0] save_G_values_out87;  // sfix37_En22
  wire signed [36:0] save_G_values_out88;  // sfix37_En22
  wire signed [36:0] save_G_values_out89;  // sfix37_En22
  wire signed [36:0] save_G_values_out90;  // sfix37_En22
  wire signed [36:0] save_G_values_out91;  // sfix37_En22
  wire signed [36:0] save_G_values_out92;  // sfix37_En22
  wire signed [36:0] save_G_values_out93;  // sfix37_En22
  wire signed [36:0] save_G_values_out94;  // sfix37_En22
  wire signed [36:0] save_G_values_out95;  // sfix37_En22
  wire signed [36:0] save_G_values_out96;  // sfix37_En22
  wire signed [36:0] save_G_values_out97;  // sfix37_En22
  wire signed [36:0] save_G_values_out98;  // sfix37_En22
  wire signed [36:0] save_G_values_out99;  // sfix37_En22
  wire signed [36:0] save_G_values_out100;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out1;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out2;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out3;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out4;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out5;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out6;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out7;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out8;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out9;  // sfix37_En22
  wire signed [36:0] switching_G_values1_out10;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out1;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out2;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out3;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out4;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out5;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out6;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out7;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out8;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out9;  // sfix37_En22
  wire signed [36:0] switching_G_values2_out10;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out1_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out1_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out2_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out2_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out3_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out3_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out4_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out4_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out5_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out5_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out6_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out6_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out7_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out7_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out8_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out8_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out9_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out9_im;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out10_re;  // sfix37_En22
  wire signed [36:0] DFT5_block_IDFT_out10_im;  // sfix37_En22


  save_DFT50_swapping_values u_save_DFT50_swapping_values (.clk(clk),
                                                           .reset_x(reset_x),
                                                           .enb(enb),
                                                           .In1_re(In1_re),  // sfix37_En22
                                                           .In1_im(In1_im),  // sfix37_En22
                                                           .In2_re(In2_re),  // sfix37_En22
                                                           .In2_im(In2_im),  // sfix37_En22
                                                           .In3_re(In3_re),  // sfix37_En22
                                                           .In3_im(In3_im),  // sfix37_En22
                                                           .In4_re(In4_re),  // sfix37_En22
                                                           .In4_im(In4_im),  // sfix37_En22
                                                           .In5_re(In5_re),  // sfix37_En22
                                                           .In5_im(In5_im),  // sfix37_En22
                                                           .In6_re(In6_re),  // sfix37_En22
                                                           .In6_im(In6_im),  // sfix37_En22
                                                           .In7_re(In7_re),  // sfix37_En22
                                                           .In7_im(In7_im),  // sfix37_En22
                                                           .In8_re(In8_re),  // sfix37_En22
                                                           .In8_im(In8_im),  // sfix37_En22
                                                           .In9_re(In9_re),  // sfix37_En22
                                                           .In9_im(In9_im),  // sfix37_En22
                                                           .In10_re(In10_re),  // sfix37_En22
                                                           .In10_im(In10_im),  // sfix37_En22
                                                           .In11_re(In11_re),  // sfix37_En22
                                                           .In11_im(In11_im),  // sfix37_En22
                                                           .In12_re(In12_re),  // sfix37_En22
                                                           .In12_im(In12_im),  // sfix37_En22
                                                           .In13_re(In13_re),  // sfix37_En22
                                                           .In13_im(In13_im),  // sfix37_En22
                                                           .In14_re(In14_re),  // sfix37_En22
                                                           .In14_im(In14_im),  // sfix37_En22
                                                           .In15_re(In15_re),  // sfix37_En22
                                                           .In15_im(In15_im),  // sfix37_En22
                                                           .In16_re(In16_re),  // sfix37_En22
                                                           .In16_im(In16_im),  // sfix37_En22
                                                           .In17_re(In17_re),  // sfix37_En22
                                                           .In17_im(In17_im),  // sfix37_En22
                                                           .In18_re(In18_re),  // sfix37_En22
                                                           .In18_im(In18_im),  // sfix37_En22
                                                           .In19_re(In19_re),  // sfix37_En22
                                                           .In19_im(In19_im),  // sfix37_En22
                                                           .In20_re(In20_re),  // sfix37_En22
                                                           .In20_im(In20_im),  // sfix37_En22
                                                           .In21_re(In21_re),  // sfix37_En22
                                                           .In21_im(In21_im),  // sfix37_En22
                                                           .In22_re(In22_re),  // sfix37_En22
                                                           .In22_im(In22_im),  // sfix37_En22
                                                           .In23_re(In23_re),  // sfix37_En22
                                                           .In23_im(In23_im),  // sfix37_En22
                                                           .In24_re(In24_re),  // sfix37_En22
                                                           .In24_im(In24_im),  // sfix37_En22
                                                           .In25_re(In25_re),  // sfix37_En22
                                                           .In25_im(In25_im),  // sfix37_En22
                                                           .In26(In29),  // uint8
                                                           .Out1_re(save_DFT50_swapping_values_out1_re),  // sfix37_En22
                                                           .Out1_im(save_DFT50_swapping_values_out1_im),  // sfix37_En22
                                                           .Out2_re(save_DFT50_swapping_values_out2_re),  // sfix37_En22
                                                           .Out2_im(save_DFT50_swapping_values_out2_im),  // sfix37_En22
                                                           .Out3_re(save_DFT50_swapping_values_out3_re),  // sfix37_En22
                                                           .Out3_im(save_DFT50_swapping_values_out3_im),  // sfix37_En22
                                                           .Out4_re(save_DFT50_swapping_values_out4_re),  // sfix37_En22
                                                           .Out4_im(save_DFT50_swapping_values_out4_im),  // sfix37_En22
                                                           .Out5_re(save_DFT50_swapping_values_out5_re),  // sfix37_En22
                                                           .Out5_im(save_DFT50_swapping_values_out5_im),  // sfix37_En22
                                                           .Out6_re(save_DFT50_swapping_values_out6_re),  // sfix37_En22
                                                           .Out6_im(save_DFT50_swapping_values_out6_im),  // sfix37_En22
                                                           .Out7_re(save_DFT50_swapping_values_out7_re),  // sfix37_En22
                                                           .Out7_im(save_DFT50_swapping_values_out7_im),  // sfix37_En22
                                                           .Out8_re(save_DFT50_swapping_values_out8_re),  // sfix37_En22
                                                           .Out8_im(save_DFT50_swapping_values_out8_im),  // sfix37_En22
                                                           .Out9_re(save_DFT50_swapping_values_out9_re),  // sfix37_En22
                                                           .Out9_im(save_DFT50_swapping_values_out9_im),  // sfix37_En22
                                                           .Out10_re(save_DFT50_swapping_values_out10_re),  // sfix37_En22
                                                           .Out10_im(save_DFT50_swapping_values_out10_im),  // sfix37_En22
                                                           .Out11_re(save_DFT50_swapping_values_out11_re),  // sfix37_En22
                                                           .Out11_im(save_DFT50_swapping_values_out11_im),  // sfix37_En22
                                                           .Out12_re(save_DFT50_swapping_values_out12_re),  // sfix37_En22
                                                           .Out12_im(save_DFT50_swapping_values_out12_im),  // sfix37_En22
                                                           .Out13_re(save_DFT50_swapping_values_out13_re),  // sfix37_En22
                                                           .Out13_im(save_DFT50_swapping_values_out13_im),  // sfix37_En22
                                                           .Out14_re(save_DFT50_swapping_values_out14_re),  // sfix37_En22
                                                           .Out14_im(save_DFT50_swapping_values_out14_im),  // sfix37_En22
                                                           .Out15_re(save_DFT50_swapping_values_out15_re),  // sfix37_En22
                                                           .Out15_im(save_DFT50_swapping_values_out15_im),  // sfix37_En22
                                                           .Out16_re(save_DFT50_swapping_values_out16_re),  // sfix37_En22
                                                           .Out16_im(save_DFT50_swapping_values_out16_im),  // sfix37_En22
                                                           .Out17_re(save_DFT50_swapping_values_out17_re),  // sfix37_En22
                                                           .Out17_im(save_DFT50_swapping_values_out17_im),  // sfix37_En22
                                                           .Out18_re(save_DFT50_swapping_values_out18_re),  // sfix37_En22
                                                           .Out18_im(save_DFT50_swapping_values_out18_im),  // sfix37_En22
                                                           .Out19_re(save_DFT50_swapping_values_out19_re),  // sfix37_En22
                                                           .Out19_im(save_DFT50_swapping_values_out19_im),  // sfix37_En22
                                                           .Out20_re(save_DFT50_swapping_values_out20_re),  // sfix37_En22
                                                           .Out20_im(save_DFT50_swapping_values_out20_im),  // sfix37_En22
                                                           .Out21_re(save_DFT50_swapping_values_out21_re),  // sfix37_En22
                                                           .Out21_im(save_DFT50_swapping_values_out21_im),  // sfix37_En22
                                                           .Out22_re(save_DFT50_swapping_values_out22_re),  // sfix37_En22
                                                           .Out22_im(save_DFT50_swapping_values_out22_im),  // sfix37_En22
                                                           .Out23_re(save_DFT50_swapping_values_out23_re),  // sfix37_En22
                                                           .Out23_im(save_DFT50_swapping_values_out23_im),  // sfix37_En22
                                                           .Out24_re(save_DFT50_swapping_values_out24_re),  // sfix37_En22
                                                           .Out24_im(save_DFT50_swapping_values_out24_im),  // sfix37_En22
                                                           .Out25_re(save_DFT50_swapping_values_out25_re),  // sfix37_En22
                                                           .Out25_im(save_DFT50_swapping_values_out25_im)  // sfix37_En22
                                                           );

  switching_DFT50_swapping_values u_switching_DFT50_swapping_values (.clk(clk),
                                                                     .reset_x(reset_x),
                                                                     .enb(enb),
                                                                     .In1_re(save_DFT50_swapping_values_out1_re),  // sfix37_En22
                                                                     .In1_im(save_DFT50_swapping_values_out1_im),  // sfix37_En22
                                                                     .In2_re(save_DFT50_swapping_values_out2_re),  // sfix37_En22
                                                                     .In2_im(save_DFT50_swapping_values_out2_im),  // sfix37_En22
                                                                     .In3_re(save_DFT50_swapping_values_out3_re),  // sfix37_En22
                                                                     .In3_im(save_DFT50_swapping_values_out3_im),  // sfix37_En22
                                                                     .In4_re(save_DFT50_swapping_values_out4_re),  // sfix37_En22
                                                                     .In4_im(save_DFT50_swapping_values_out4_im),  // sfix37_En22
                                                                     .In5_re(save_DFT50_swapping_values_out5_re),  // sfix37_En22
                                                                     .In5_im(save_DFT50_swapping_values_out5_im),  // sfix37_En22
                                                                     .In6_re(save_DFT50_swapping_values_out6_re),  // sfix37_En22
                                                                     .In6_im(save_DFT50_swapping_values_out6_im),  // sfix37_En22
                                                                     .In7_re(save_DFT50_swapping_values_out7_re),  // sfix37_En22
                                                                     .In7_im(save_DFT50_swapping_values_out7_im),  // sfix37_En22
                                                                     .In8_re(save_DFT50_swapping_values_out8_re),  // sfix37_En22
                                                                     .In8_im(save_DFT50_swapping_values_out8_im),  // sfix37_En22
                                                                     .In9_re(save_DFT50_swapping_values_out9_re),  // sfix37_En22
                                                                     .In9_im(save_DFT50_swapping_values_out9_im),  // sfix37_En22
                                                                     .In10_re(save_DFT50_swapping_values_out10_re),  // sfix37_En22
                                                                     .In10_im(save_DFT50_swapping_values_out10_im),  // sfix37_En22
                                                                     .In11_re(save_DFT50_swapping_values_out11_re),  // sfix37_En22
                                                                     .In11_im(save_DFT50_swapping_values_out11_im),  // sfix37_En22
                                                                     .In12_re(save_DFT50_swapping_values_out12_re),  // sfix37_En22
                                                                     .In12_im(save_DFT50_swapping_values_out12_im),  // sfix37_En22
                                                                     .In13_re(save_DFT50_swapping_values_out13_re),  // sfix37_En22
                                                                     .In13_im(save_DFT50_swapping_values_out13_im),  // sfix37_En22
                                                                     .In14_re(save_DFT50_swapping_values_out14_re),  // sfix37_En22
                                                                     .In14_im(save_DFT50_swapping_values_out14_im),  // sfix37_En22
                                                                     .In15_re(save_DFT50_swapping_values_out15_re),  // sfix37_En22
                                                                     .In15_im(save_DFT50_swapping_values_out15_im),  // sfix37_En22
                                                                     .In16_re(save_DFT50_swapping_values_out16_re),  // sfix37_En22
                                                                     .In16_im(save_DFT50_swapping_values_out16_im),  // sfix37_En22
                                                                     .In17_re(save_DFT50_swapping_values_out17_re),  // sfix37_En22
                                                                     .In17_im(save_DFT50_swapping_values_out17_im),  // sfix37_En22
                                                                     .In18_re(save_DFT50_swapping_values_out18_re),  // sfix37_En22
                                                                     .In18_im(save_DFT50_swapping_values_out18_im),  // sfix37_En22
                                                                     .In19_re(save_DFT50_swapping_values_out19_re),  // sfix37_En22
                                                                     .In19_im(save_DFT50_swapping_values_out19_im),  // sfix37_En22
                                                                     .In20_re(save_DFT50_swapping_values_out20_re),  // sfix37_En22
                                                                     .In20_im(save_DFT50_swapping_values_out20_im),  // sfix37_En22
                                                                     .In21_re(save_DFT50_swapping_values_out21_re),  // sfix37_En22
                                                                     .In21_im(save_DFT50_swapping_values_out21_im),  // sfix37_En22
                                                                     .In22_re(save_DFT50_swapping_values_out22_re),  // sfix37_En22
                                                                     .In22_im(save_DFT50_swapping_values_out22_im),  // sfix37_En22
                                                                     .In23_re(save_DFT50_swapping_values_out23_re),  // sfix37_En22
                                                                     .In23_im(save_DFT50_swapping_values_out23_im),  // sfix37_En22
                                                                     .In24_re(save_DFT50_swapping_values_out24_re),  // sfix37_En22
                                                                     .In24_im(save_DFT50_swapping_values_out24_im),  // sfix37_En22
                                                                     .In25_re(save_DFT50_swapping_values_out25_re),  // sfix37_En22
                                                                     .In25_im(save_DFT50_swapping_values_out25_im),  // sfix37_En22
                                                                     .In26(In27),  // uint8
                                                                     .Out1_re(switching_DFT50_swapping_values_out1_re),  // sfix37_En22
                                                                     .Out1_im(switching_DFT50_swapping_values_out1_im),  // sfix37_En22
                                                                     .Out2_re(switching_DFT50_swapping_values_out2_re),  // sfix37_En22
                                                                     .Out2_im(switching_DFT50_swapping_values_out2_im),  // sfix37_En22
                                                                     .Out3_re(switching_DFT50_swapping_values_out3_re),  // sfix37_En22
                                                                     .Out3_im(switching_DFT50_swapping_values_out3_im),  // sfix37_En22
                                                                     .Out4_re(switching_DFT50_swapping_values_out4_re),  // sfix37_En22
                                                                     .Out4_im(switching_DFT50_swapping_values_out4_im),  // sfix37_En22
                                                                     .Out5_re(switching_DFT50_swapping_values_out5_re),  // sfix37_En22
                                                                     .Out5_im(switching_DFT50_swapping_values_out5_im)  // sfix37_En22
                                                                     );

  assign Constant4_out1 = 37'sh000013C6EF;



  assign Constant5_out1 = 37'sh000033C6EF;



  assign Constant6_out1 = 37'sh0000259E45;



  assign Constant7_out1 = 37'sh00003CDE1A;



  DFT10_block_2 u_DFT10_block_2 (.clk(clk),
                                 .reset_x(reset_x),
                                 .enb(enb),
                                 .x10_0_0_re(switching_DFT50_swapping_values_out1_re),  // sfix37_En22
                                 .x10_0_0_im(switching_DFT50_swapping_values_out1_im),  // sfix37_En22
                                 .x10_1_0_re(switching_DFT50_swapping_values_out2_re),  // sfix37_En22
                                 .x10_1_0_im(switching_DFT50_swapping_values_out2_im),  // sfix37_En22
                                 .x10_0_1_re(switching_DFT50_swapping_values_out3_re),  // sfix37_En22
                                 .x10_0_1_im(switching_DFT50_swapping_values_out3_im),  // sfix37_En22
                                 .x10_1_1_re(switching_DFT50_swapping_values_out4_re),  // sfix37_En22
                                 .x10_1_1_im(switching_DFT50_swapping_values_out4_im),  // sfix37_En22
                                 .x10_0_2_re(switching_DFT50_swapping_values_out5_re),  // sfix37_En22
                                 .x10_0_2_im(switching_DFT50_swapping_values_out5_im),  // sfix37_En22
                                 .x10_1_2_re(x10_1_4_re),  // ufix1
                                 .x10_1_2_im(x10_1_4_im),  // ufix1
                                 .x10_0_3_re(x10_1_4_re),  // ufix1
                                 .x10_0_3_im(x10_1_4_im),  // ufix1
                                 .x10_1_3_re(x10_1_4_re),  // ufix1
                                 .x10_1_3_im(x10_1_4_im),  // ufix1
                                 .x10_0_4_re(x10_1_4_re),  // ufix1
                                 .x10_0_4_im(x10_1_4_im),  // ufix1
                                 .x10_1_4_re(x10_1_4_re),  // ufix1
                                 .x10_1_4_im(x10_1_4_im),  // ufix1
                                 .alpha0_309017(Constant4_out1),  // sfix37_En22
                                 .alpha0_809017(Constant5_out1),  // sfix37_En22
                                 .alpha0_587785(Constant6_out1),  // sfix37_En22
                                 .alpha0_951056(Constant7_out1),  // sfix37_En22
                                 .X10_0_re(DFT10_block_2_out1_re),  // sfix37_En22
                                 .X10_0_im(DFT10_block_2_out1_im),  // sfix37_En22
                                 .X10_1_re(DFT10_block_2_out2_re),  // sfix37_En22
                                 .X10_1_im(DFT10_block_2_out2_im),  // sfix37_En22
                                 .X10_2_re(DFT10_block_2_out3_re),  // sfix37_En22
                                 .X10_2_im(DFT10_block_2_out3_im),  // sfix37_En22
                                 .X10_3_re(DFT10_block_2_out4_re),  // sfix37_En22
                                 .X10_3_im(DFT10_block_2_out4_im),  // sfix37_En22
                                 .X10_4_re(DFT10_block_2_out5_re),  // sfix37_En22
                                 .X10_4_im(DFT10_block_2_out5_im),  // sfix37_En22
                                 .X10_5_re(DFT10_block_2_out6_re),  // sfix37_En22
                                 .X10_5_im(DFT10_block_2_out6_im),  // sfix37_En22
                                 .X10_6_re(DFT10_block_2_out7_re),  // sfix37_En22
                                 .X10_6_im(DFT10_block_2_out7_im),  // sfix37_En22
                                 .X10_7_re(DFT10_block_2_out8_re),  // sfix37_En22
                                 .X10_7_im(DFT10_block_2_out8_im),  // sfix37_En22
                                 .X10_8_re(DFT10_block_2_out9_re),  // sfix37_En22
                                 .X10_8_im(DFT10_block_2_out9_im),  // sfix37_En22
                                 .X10_9_re(DFT10_block_2_out10_re),  // sfix37_En22
                                 .X10_9_im(DFT10_block_2_out10_im)  // sfix37_En22
                                 );

  W50_block u_W50 (.clk(clk),
                   .reset_x(reset_x),
                   .enb(enb),
                   .X10_0_re(DFT10_block_2_out1_re),  // sfix37_En22
                   .X10_0_im(DFT10_block_2_out1_im),  // sfix37_En22
                   .X10_1_re(DFT10_block_2_out2_re),  // sfix37_En22
                   .X10_1_im(DFT10_block_2_out2_im),  // sfix37_En22
                   .X10_2_re(DFT10_block_2_out3_re),  // sfix37_En22
                   .X10_2_im(DFT10_block_2_out3_im),  // sfix37_En22
                   .X10_3_re(DFT10_block_2_out4_re),  // sfix37_En22
                   .X10_3_im(DFT10_block_2_out4_im),  // sfix37_En22
                   .X10_4_re(DFT10_block_2_out5_re),  // sfix37_En22
                   .X10_4_im(DFT10_block_2_out5_im),  // sfix37_En22
                   .X10_5_re(DFT10_block_2_out6_re),  // sfix37_En22
                   .X10_5_im(DFT10_block_2_out6_im),  // sfix37_En22
                   .X10_6_re(DFT10_block_2_out7_re),  // sfix37_En22
                   .X10_6_im(DFT10_block_2_out7_im),  // sfix37_En22
                   .X10_7_re(DFT10_block_2_out8_re),  // sfix37_En22
                   .X10_7_im(DFT10_block_2_out8_im),  // sfix37_En22
                   .X10_8_re(DFT10_block_2_out9_re),  // sfix37_En22
                   .X10_8_im(DFT10_block_2_out9_im),  // sfix37_En22
                   .X10_9_re(DFT10_block_2_out10_re),  // sfix37_En22
                   .X10_9_im(DFT10_block_2_out10_im),  // sfix37_En22
                   .Out1_re(W50_out1_re),  // sfix37_En22
                   .Out1_im(W50_out1_im),  // sfix37_En22
                   .Out2_re(W50_out2_re),  // sfix37_En22
                   .Out2_im(W50_out2_im),  // sfix37_En22
                   .Out3_re(W50_out3_re),  // sfix37_En22
                   .Out3_im(W50_out3_im),  // sfix37_En22
                   .Out4_re(W50_out4_re),  // sfix37_En22
                   .Out4_im(W50_out4_im),  // sfix37_En22
                   .Out5_re(W50_out5_re),  // sfix37_En22
                   .Out5_im(W50_out5_im),  // sfix37_En22
                   .Out6_re(W50_out6_re),  // sfix37_En22
                   .Out6_im(W50_out6_im),  // sfix37_En22
                   .Out7_re(W50_out7_re),  // sfix37_En22
                   .Out7_im(W50_out7_im),  // sfix37_En22
                   .Out8_re(W50_out8_re),  // sfix37_En22
                   .Out8_im(W50_out8_im),  // sfix37_En22
                   .Out9_re(W50_out9_re),  // sfix37_En22
                   .Out9_im(W50_out9_im),  // sfix37_En22
                   .Out10_re(W50_out10_re),  // sfix37_En22
                   .Out10_im(W50_out10_im)  // sfix37_En22
                   );

  save_G_values u_save_G_values (.clk(clk),
                                 .reset_x(reset_x),
                                 .enb(enb),
                                 .din(W50_out1_re),  // sfix37_En22
                                 .din1(W50_out1_im),  // sfix37_En22
                                 .din2(W50_out2_re),  // sfix37_En22
                                 .din3(W50_out2_im),  // sfix37_En22
                                 .din4(W50_out3_re),  // sfix37_En22
                                 .din5(W50_out3_im),  // sfix37_En22
                                 .din6(W50_out4_re),  // sfix37_En22
                                 .din7(W50_out4_im),  // sfix37_En22
                                 .din8(W50_out5_re),  // sfix37_En22
                                 .din9(W50_out5_im),  // sfix37_En22
                                 .din10(W50_out6_re),  // sfix37_En22
                                 .din11(W50_out6_im),  // sfix37_En22
                                 .din12(W50_out7_re),  // sfix37_En22
                                 .din13(W50_out7_im),  // sfix37_En22
                                 .din14(W50_out8_re),  // sfix37_En22
                                 .din15(W50_out8_im),  // sfix37_En22
                                 .din16(W50_out9_re),  // sfix37_En22
                                 .din17(W50_out9_im),  // sfix37_En22
                                 .In19(In27),  // uint8
                                 .din18(W50_out10_re),  // sfix37_En22
                                 .din19(W50_out10_im),  // sfix37_En22
                                 .real_G_0_0(save_G_values_out1),  // sfix37_En22
                                 .dout1(save_G_values_out2),  // sfix37_En22
                                 .real_G_1_0(save_G_values_out3),  // sfix37_En22
                                 .dout3(save_G_values_out4),  // sfix37_En22
                                 .real_G_2_0(save_G_values_out5),  // sfix37_En22
                                 .dout5(save_G_values_out6),  // sfix37_En22
                                 .real_G_3_0(save_G_values_out7),  // sfix37_En22
                                 .dout7(save_G_values_out8),  // sfix37_En22
                                 .real_G_4_0(save_G_values_out9),  // sfix37_En22
                                 .dout9(save_G_values_out10),  // sfix37_En22
                                 .real_G_0_1(save_G_values_out11),  // sfix37_En22
                                 .dout11(save_G_values_out12),  // sfix37_En22
                                 .real_G_1_1(save_G_values_out13),  // sfix37_En22
                                 .dout13(save_G_values_out14),  // sfix37_En22
                                 .real_G_2_1(save_G_values_out15),  // sfix37_En22
                                 .dout15(save_G_values_out16),  // sfix37_En22
                                 .real_G_3_1(save_G_values_out17),  // sfix37_En22
                                 .dout17(save_G_values_out18),  // sfix37_En22
                                 .real_G_4_1(save_G_values_out19),  // sfix37_En22
                                 .dout19(save_G_values_out20),  // sfix37_En22
                                 .real_G_0_2(save_G_values_out21),  // sfix37_En22
                                 .dout21(save_G_values_out22),  // sfix37_En22
                                 .real_G_1_2(save_G_values_out23),  // sfix37_En22
                                 .dout23(save_G_values_out24),  // sfix37_En22
                                 .real_G_2_2(save_G_values_out25),  // sfix37_En22
                                 .dout25(save_G_values_out26),  // sfix37_En22
                                 .real_G_3_2(save_G_values_out27),  // sfix37_En22
                                 .dout27(save_G_values_out28),  // sfix37_En22
                                 .real_G_4_2(save_G_values_out29),  // sfix37_En22
                                 .dout29(save_G_values_out30),  // sfix37_En22
                                 .real_G_0_3(save_G_values_out31),  // sfix37_En22
                                 .dout31(save_G_values_out32),  // sfix37_En22
                                 .real_G_1_3(save_G_values_out33),  // sfix37_En22
                                 .dout33(save_G_values_out34),  // sfix37_En22
                                 .real_G_2_3(save_G_values_out35),  // sfix37_En22
                                 .dout35(save_G_values_out36),  // sfix37_En22
                                 .real_G_3_3(save_G_values_out37),  // sfix37_En22
                                 .dout37(save_G_values_out38),  // sfix37_En22
                                 .real_G_4_3(save_G_values_out39),  // sfix37_En22
                                 .dout39(save_G_values_out40),  // sfix37_En22
                                 .real_G_0_4(save_G_values_out41),  // sfix37_En22
                                 .dout41(save_G_values_out42),  // sfix37_En22
                                 .real_G_1_4(save_G_values_out43),  // sfix37_En22
                                 .dout43(save_G_values_out44),  // sfix37_En22
                                 .real_G_2_4(save_G_values_out45),  // sfix37_En22
                                 .dout45(save_G_values_out46),  // sfix37_En22
                                 .real_G_3_4(save_G_values_out47),  // sfix37_En22
                                 .dout47(save_G_values_out48),  // sfix37_En22
                                 .real_G_4_4(save_G_values_out49),  // sfix37_En22
                                 .dout49(save_G_values_out50),  // sfix37_En22
                                 .real_G_0_5(save_G_values_out51),  // sfix37_En22
                                 .dout51(save_G_values_out52),  // sfix37_En22
                                 .real_G_1_5(save_G_values_out53),  // sfix37_En22
                                 .dout53(save_G_values_out54),  // sfix37_En22
                                 .real_G_2_5(save_G_values_out55),  // sfix37_En22
                                 .dout55(save_G_values_out56),  // sfix37_En22
                                 .real_G_3_5(save_G_values_out57),  // sfix37_En22
                                 .dout57(save_G_values_out58),  // sfix37_En22
                                 .real_G_4_5(save_G_values_out59),  // sfix37_En22
                                 .dout59(save_G_values_out60),  // sfix37_En22
                                 .real_G_0_6(save_G_values_out61),  // sfix37_En22
                                 .dout61(save_G_values_out62),  // sfix37_En22
                                 .real_G_1_6(save_G_values_out63),  // sfix37_En22
                                 .dout63(save_G_values_out64),  // sfix37_En22
                                 .real_G_2_6(save_G_values_out65),  // sfix37_En22
                                 .dout65(save_G_values_out66),  // sfix37_En22
                                 .real_G_3_6(save_G_values_out67),  // sfix37_En22
                                 .dout67(save_G_values_out68),  // sfix37_En22
                                 .real_G_4_6(save_G_values_out69),  // sfix37_En22
                                 .dout69(save_G_values_out70),  // sfix37_En22
                                 .real_G_0_7(save_G_values_out71),  // sfix37_En22
                                 .dout71(save_G_values_out72),  // sfix37_En22
                                 .real_G_1_7(save_G_values_out73),  // sfix37_En22
                                 .dout73(save_G_values_out74),  // sfix37_En22
                                 .real_G_2_7(save_G_values_out75),  // sfix37_En22
                                 .dout75(save_G_values_out76),  // sfix37_En22
                                 .real_G_3_7(save_G_values_out77),  // sfix37_En22
                                 .dout77(save_G_values_out78),  // sfix37_En22
                                 .real_G_4_7(save_G_values_out79),  // sfix37_En22
                                 .dout79(save_G_values_out80),  // sfix37_En22
                                 .real_G_0_8(save_G_values_out81),  // sfix37_En22
                                 .dout81(save_G_values_out82),  // sfix37_En22
                                 .real_G_1_8(save_G_values_out83),  // sfix37_En22
                                 .dout83(save_G_values_out84),  // sfix37_En22
                                 .real_G_2_8(save_G_values_out85),  // sfix37_En22
                                 .dout85(save_G_values_out86),  // sfix37_En22
                                 .real_G_3_8(save_G_values_out87),  // sfix37_En22
                                 .dout87(save_G_values_out88),  // sfix37_En22
                                 .real_G_4_8(save_G_values_out89),  // sfix37_En22
                                 .dout89(save_G_values_out90),  // sfix37_En22
                                 .real_G_0_9(save_G_values_out91),  // sfix37_En22
                                 .dout91(save_G_values_out92),  // sfix37_En22
                                 .real_G_1_9(save_G_values_out93),  // sfix37_En22
                                 .dout93(save_G_values_out94),  // sfix37_En22
                                 .real_G_2_9(save_G_values_out95),  // sfix37_En22
                                 .dout95(save_G_values_out96),  // sfix37_En22
                                 .real_G_3_9(save_G_values_out97),  // sfix37_En22
                                 .dout97(save_G_values_out98),  // sfix37_En22
                                 .real_G_4_9(save_G_values_out99),  // sfix37_En22
                                 .dout99(save_G_values_out100)  // sfix37_En22
                                 );

  switching_G_values1 u_switching_G_values1 (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .In1(save_G_values_out1),  // sfix37_En22
                                             .In2(save_G_values_out2),  // sfix37_En22
                                             .real_G_1_0(save_G_values_out3),  // sfix37_En22
                                             .dout3(save_G_values_out4),  // sfix37_En22
                                             .real_G_2_0(save_G_values_out5),  // sfix37_En22
                                             .dout5(save_G_values_out6),  // sfix37_En22
                                             .real_G_3_0(save_G_values_out7),  // sfix37_En22
                                             .dout7(save_G_values_out8),  // sfix37_En22
                                             .real_G_4_0(save_G_values_out9),  // sfix37_En22
                                             .dout9(save_G_values_out10),  // sfix37_En22
                                             .In11(save_G_values_out11),  // sfix37_En22
                                             .In12(save_G_values_out12),  // sfix37_En22
                                             .real_G_1_1(save_G_values_out13),  // sfix37_En22
                                             .dout13(save_G_values_out14),  // sfix37_En22
                                             .real_G_2_1(save_G_values_out15),  // sfix37_En22
                                             .dout15(save_G_values_out16),  // sfix37_En22
                                             .real_G_3_1(save_G_values_out17),  // sfix37_En22
                                             .dout17(save_G_values_out18),  // sfix37_En22
                                             .real_G_4_1(save_G_values_out19),  // sfix37_En22
                                             .dout19(save_G_values_out20),  // sfix37_En22
                                             .In21(save_G_values_out21),  // sfix37_En22
                                             .In22(save_G_values_out22),  // sfix37_En22
                                             .real_G_1_2(save_G_values_out23),  // sfix37_En22
                                             .dout23(save_G_values_out24),  // sfix37_En22
                                             .real_G_2_2(save_G_values_out25),  // sfix37_En22
                                             .dout25(save_G_values_out26),  // sfix37_En22
                                             .real_G_3_2(save_G_values_out27),  // sfix37_En22
                                             .dout27(save_G_values_out28),  // sfix37_En22
                                             .real_G_4_2(save_G_values_out29),  // sfix37_En22
                                             .dout29(save_G_values_out30),  // sfix37_En22
                                             .In31(save_G_values_out31),  // sfix37_En22
                                             .In32(save_G_values_out32),  // sfix37_En22
                                             .real_G_1_3(save_G_values_out33),  // sfix37_En22
                                             .dout33(save_G_values_out34),  // sfix37_En22
                                             .real_G_2_3(save_G_values_out35),  // sfix37_En22
                                             .dout35(save_G_values_out36),  // sfix37_En22
                                             .real_G_3_3(save_G_values_out37),  // sfix37_En22
                                             .dout37(save_G_values_out38),  // sfix37_En22
                                             .real_G_4_3(save_G_values_out39),  // sfix37_En22
                                             .dout39(save_G_values_out40),  // sfix37_En22
                                             .In41(save_G_values_out41),  // sfix37_En22
                                             .In42(save_G_values_out42),  // sfix37_En22
                                             .real_G_1_4(save_G_values_out43),  // sfix37_En22
                                             .dout43(save_G_values_out44),  // sfix37_En22
                                             .real_G_2_4(save_G_values_out45),  // sfix37_En22
                                             .dout45(save_G_values_out46),  // sfix37_En22
                                             .real_G_3_4(save_G_values_out47),  // sfix37_En22
                                             .dout47(save_G_values_out48),  // sfix37_En22
                                             .real_G_4_4(save_G_values_out49),  // sfix37_En22
                                             .dout49(save_G_values_out50),  // sfix37_En22
                                             .In51(In28),  // uint8
                                             .Out1(switching_G_values1_out1),  // sfix37_En22
                                             .Out2(switching_G_values1_out2),  // sfix37_En22
                                             .Out3(switching_G_values1_out3),  // sfix37_En22
                                             .Out4(switching_G_values1_out4),  // sfix37_En22
                                             .Out5(switching_G_values1_out5),  // sfix37_En22
                                             .Out6(switching_G_values1_out6),  // sfix37_En22
                                             .Out7(switching_G_values1_out7),  // sfix37_En22
                                             .Out8(switching_G_values1_out8),  // sfix37_En22
                                             .Out9(switching_G_values1_out9),  // sfix37_En22
                                             .Out10(switching_G_values1_out10)  // sfix37_En22
                                             );

  switching_G_values2 u_switching_G_values2 (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .In1(save_G_values_out51),  // sfix37_En22
                                             .In2(save_G_values_out52),  // sfix37_En22
                                             .real_G_1_0(save_G_values_out53),  // sfix37_En22
                                             .dout3(save_G_values_out54),  // sfix37_En22
                                             .real_G_2_0(save_G_values_out55),  // sfix37_En22
                                             .dout5(save_G_values_out56),  // sfix37_En22
                                             .real_G_3_0(save_G_values_out57),  // sfix37_En22
                                             .dout7(save_G_values_out58),  // sfix37_En22
                                             .real_G_4_0(save_G_values_out59),  // sfix37_En22
                                             .dout9(save_G_values_out60),  // sfix37_En22
                                             .In11(save_G_values_out61),  // sfix37_En22
                                             .In12(save_G_values_out62),  // sfix37_En22
                                             .real_G_1_1(save_G_values_out63),  // sfix37_En22
                                             .dout13(save_G_values_out64),  // sfix37_En22
                                             .real_G_2_1(save_G_values_out65),  // sfix37_En22
                                             .dout15(save_G_values_out66),  // sfix37_En22
                                             .real_G_3_1(save_G_values_out67),  // sfix37_En22
                                             .dout17(save_G_values_out68),  // sfix37_En22
                                             .real_G_4_1(save_G_values_out69),  // sfix37_En22
                                             .dout19(save_G_values_out70),  // sfix37_En22
                                             .In21(save_G_values_out71),  // sfix37_En22
                                             .In22(save_G_values_out72),  // sfix37_En22
                                             .real_G_1_2(save_G_values_out73),  // sfix37_En22
                                             .dout23(save_G_values_out74),  // sfix37_En22
                                             .real_G_2_2(save_G_values_out75),  // sfix37_En22
                                             .dout25(save_G_values_out76),  // sfix37_En22
                                             .real_G_3_2(save_G_values_out77),  // sfix37_En22
                                             .dout27(save_G_values_out78),  // sfix37_En22
                                             .real_G_4_2(save_G_values_out79),  // sfix37_En22
                                             .dout29(save_G_values_out80),  // sfix37_En22
                                             .In31(save_G_values_out81),  // sfix37_En22
                                             .In32(save_G_values_out82),  // sfix37_En22
                                             .real_G_1_3(save_G_values_out83),  // sfix37_En22
                                             .dout33(save_G_values_out84),  // sfix37_En22
                                             .real_G_2_3(save_G_values_out85),  // sfix37_En22
                                             .dout35(save_G_values_out86),  // sfix37_En22
                                             .real_G_3_3(save_G_values_out87),  // sfix37_En22
                                             .dout37(save_G_values_out88),  // sfix37_En22
                                             .real_G_4_3(save_G_values_out89),  // sfix37_En22
                                             .dout39(save_G_values_out90),  // sfix37_En22
                                             .In41(save_G_values_out91),  // sfix37_En22
                                             .In42(save_G_values_out92),  // sfix37_En22
                                             .real_G_1_4(save_G_values_out93),  // sfix37_En22
                                             .dout43(save_G_values_out94),  // sfix37_En22
                                             .real_G_2_4(save_G_values_out95),  // sfix37_En22
                                             .dout45(save_G_values_out96),  // sfix37_En22
                                             .real_G_3_4(save_G_values_out97),  // sfix37_En22
                                             .dout47(save_G_values_out98),  // sfix37_En22
                                             .real_G_4_4(save_G_values_out99),  // sfix37_En22
                                             .dout49(save_G_values_out100),  // sfix37_En22
                                             .In51(In28),  // uint8
                                             .Out1(switching_G_values2_out1),  // sfix37_En22
                                             .Out2(switching_G_values2_out2),  // sfix37_En22
                                             .Out3(switching_G_values2_out3),  // sfix37_En22
                                             .Out4(switching_G_values2_out4),  // sfix37_En22
                                             .Out5(switching_G_values2_out5),  // sfix37_En22
                                             .Out6(switching_G_values2_out6),  // sfix37_En22
                                             .Out7(switching_G_values2_out7),  // sfix37_En22
                                             .Out8(switching_G_values2_out8),  // sfix37_En22
                                             .Out9(switching_G_values2_out9),  // sfix37_En22
                                             .Out10(switching_G_values2_out10)  // sfix37_En22
                                             );

  DFT5_block_IDFT u_DFT5_block_IDFT (.clk(clk),
                                     .reset_x(reset_x),
                                     .enb(enb),
                                     .In1_re(switching_G_values1_out1),  // sfix37_En22
                                     .In1_im(switching_G_values1_out2),  // sfix37_En22
                                     .In2_re(switching_G_values1_out3),  // sfix37_En22
                                     .In2_im(switching_G_values1_out4),  // sfix37_En22
                                     .In3_re(switching_G_values1_out5),  // sfix37_En22
                                     .In3_im(switching_G_values1_out6),  // sfix37_En22
                                     .In4_re(switching_G_values1_out7),  // sfix37_En22
                                     .In4_im(switching_G_values1_out8),  // sfix37_En22
                                     .In5_re(switching_G_values1_out9),  // sfix37_En22
                                     .In5_im(switching_G_values1_out10),  // sfix37_En22
                                     .In6_re(switching_G_values2_out1),  // sfix37_En22
                                     .In6_im(switching_G_values2_out2),  // sfix37_En22
                                     .In7_re(switching_G_values2_out3),  // sfix37_En22
                                     .In7_im(switching_G_values2_out4),  // sfix37_En22
                                     .In8_re(switching_G_values2_out5),  // sfix37_En22
                                     .In8_im(switching_G_values2_out6),  // sfix37_En22
                                     .In9_re(switching_G_values2_out7),  // sfix37_En22
                                     .In9_im(switching_G_values2_out8),  // sfix37_En22
                                     .In10_re(switching_G_values2_out9),  // sfix37_En22
                                     .In10_im(switching_G_values2_out10),  // sfix37_En22
                                     .Out1_re(DFT5_block_IDFT_out1_re),  // sfix37_En22
                                     .Out1_im(DFT5_block_IDFT_out1_im),  // sfix37_En22
                                     .Out2_re(DFT5_block_IDFT_out2_re),  // sfix37_En22
                                     .Out2_im(DFT5_block_IDFT_out2_im),  // sfix37_En22
                                     .Out3_re(DFT5_block_IDFT_out3_re),  // sfix37_En22
                                     .Out3_im(DFT5_block_IDFT_out3_im),  // sfix37_En22
                                     .Out4_re(DFT5_block_IDFT_out4_re),  // sfix37_En22
                                     .Out4_im(DFT5_block_IDFT_out4_im),  // sfix37_En22
                                     .Out5_re(DFT5_block_IDFT_out5_re),  // sfix37_En22
                                     .Out5_im(DFT5_block_IDFT_out5_im),  // sfix37_En22
                                     .Out6_re(DFT5_block_IDFT_out6_re),  // sfix37_En22
                                     .Out6_im(DFT5_block_IDFT_out6_im),  // sfix37_En22
                                     .Out7_re(DFT5_block_IDFT_out7_re),  // sfix37_En22
                                     .Out7_im(DFT5_block_IDFT_out7_im),  // sfix37_En22
                                     .Out8_re(DFT5_block_IDFT_out8_re),  // sfix37_En22
                                     .Out8_im(DFT5_block_IDFT_out8_im),  // sfix37_En22
                                     .Out9_re(DFT5_block_IDFT_out9_re),  // sfix37_En22
                                     .Out9_im(DFT5_block_IDFT_out9_im),  // sfix37_En22
                                     .Out10_re(DFT5_block_IDFT_out10_re),  // sfix37_En22
                                     .Out10_im(DFT5_block_IDFT_out10_im)  // sfix37_En22
                                     );

  assign Out1_re = DFT5_block_IDFT_out1_re;

  assign Out1_im = DFT5_block_IDFT_out1_im;

  assign Out2_re = DFT5_block_IDFT_out2_re;

  assign Out2_im = DFT5_block_IDFT_out2_im;

  assign Out3_re = DFT5_block_IDFT_out3_re;

  assign Out3_im = DFT5_block_IDFT_out3_im;

  assign Out4_re = DFT5_block_IDFT_out4_re;

  assign Out4_im = DFT5_block_IDFT_out4_im;

  assign Out5_re = DFT5_block_IDFT_out5_re;

  assign Out5_im = DFT5_block_IDFT_out5_im;

  assign Out6_re = DFT5_block_IDFT_out6_re;

  assign Out6_im = DFT5_block_IDFT_out6_im;

  assign Out7_re = DFT5_block_IDFT_out7_re;

  assign Out7_im = DFT5_block_IDFT_out7_im;

  assign Out8_re = DFT5_block_IDFT_out8_re;

  assign Out8_im = DFT5_block_IDFT_out8_im;

  assign Out9_re = DFT5_block_IDFT_out9_re;

  assign Out9_im = DFT5_block_IDFT_out9_im;

  assign Out10_re = DFT5_block_IDFT_out10_re;

  assign Out10_im = DFT5_block_IDFT_out10_im;

endmodule  // DFT_2

