// -------------------------------------------------------------
// 
// File Name: C:\Users\Carlos Cajas\Desktop\henkindama2\newhope_cambios\FDHT.v
// Created: 2020-12-20 13:10:05
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.02
// Target subsystem base rate: 0.02
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.02
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// out1                          ce_out        0.02
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FDHT
// Source Path: newhope_cambios/FDHT
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FDHT
          (clk,
           reset_x,
           clk_enable,
           in1,
           ce_out,
           out1);


  input   clk;
  input   reset_x;
  input   clk_enable;
  input   signed [14:0] in1;  // sfix15_En5
  output  ce_out;
  output  signed [14:0] out1;  // sfix15_En5


  wire enb;
  wire signed [14:0] serial_parallel_out1;  // sfix15_En5
  wire signed [14:0] serial_parallel_out2;  // sfix15_En5
  wire signed [14:0] serial_parallel_out3;  // sfix15_En5
  wire signed [14:0] serial_parallel_out4;  // sfix15_En5
  wire signed [14:0] serial_parallel_out5;  // sfix15_En5
  wire signed [14:0] serial_parallel_out6;  // sfix15_En5
  wire signed [14:0] serial_parallel_out7;  // sfix15_En5
  wire signed [14:0] serial_parallel_out8;  // sfix15_En5
  wire signed [14:0] serial_parallel_out9;  // sfix15_En5
  wire signed [14:0] serial_parallel_out10;  // sfix15_En5
  wire signed [14:0] serial_parallel_out11;  // sfix15_En5
  wire signed [14:0] serial_parallel_out12;  // sfix15_En5
  wire signed [14:0] serial_parallel_out13;  // sfix15_En5
  wire signed [14:0] serial_parallel_out14;  // sfix15_En5
  wire signed [14:0] serial_parallel_out15;  // sfix15_En5
  wire signed [14:0] serial_parallel_out16;  // sfix15_En5
  wire signed [14:0] serial_parallel_out17;  // sfix15_En5
  wire signed [14:0] serial_parallel_out18;  // sfix15_En5
  wire signed [14:0] serial_parallel_out19;  // sfix15_En5
  wire signed [14:0] serial_parallel_out20;  // sfix15_En5
  wire signed [14:0] serial_parallel_out21;  // sfix15_En5
  wire signed [14:0] serial_parallel_out22;  // sfix15_En5
  wire signed [14:0] serial_parallel_out23;  // sfix15_En5
  wire signed [14:0] serial_parallel_out24;  // sfix15_En5
  wire signed [14:0] serial_parallel_out25;  // sfix15_En5
  wire signed [14:0] serial_parallel_out26;  // sfix15_En5
  wire signed [14:0] serial_parallel_out27;  // sfix15_En5
  wire signed [14:0] serial_parallel_out28;  // sfix15_En5
  wire signed [14:0] serial_parallel_out29;  // sfix15_En5
  wire signed [14:0] serial_parallel_out30;  // sfix15_En5
  wire signed [14:0] serial_parallel_out31;  // sfix15_En5
  wire signed [14:0] serial_parallel_out32;  // sfix15_En5
  wire signed [14:0] serial_parallel_out33;  // sfix15_En5
  wire signed [14:0] serial_parallel_out34;  // sfix15_En5
  wire signed [14:0] serial_parallel_out35;  // sfix15_En5
  wire signed [14:0] serial_parallel_out36;  // sfix15_En5
  wire signed [14:0] serial_parallel_out37;  // sfix15_En5
  wire signed [14:0] serial_parallel_out38;  // sfix15_En5
  wire signed [14:0] serial_parallel_out39;  // sfix15_En5
  wire signed [14:0] serial_parallel_out40;  // sfix15_En5
  wire signed [14:0] serial_parallel_out41;  // sfix15_En5
  wire signed [14:0] serial_parallel_out42;  // sfix15_En5
  wire signed [14:0] serial_parallel_out43;  // sfix15_En5
  wire signed [14:0] serial_parallel_out44;  // sfix15_En5
  wire signed [14:0] serial_parallel_out45;  // sfix15_En5
  wire signed [14:0] serial_parallel_out46;  // sfix15_En5
  wire signed [14:0] serial_parallel_out47;  // sfix15_En5
  wire signed [14:0] serial_parallel_out48;  // sfix15_En5
  wire signed [14:0] serial_parallel_out49;  // sfix15_En5
  wire signed [14:0] serial_parallel_out50;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out1;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out2;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out3;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out4;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out5;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out6;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out7;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out8;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out9;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out10;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out11;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out12;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out13;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out14;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out15;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out16;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out17;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out18;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out19;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out20;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out21;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out22;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out23;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out24;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out25;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out26;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out27;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out28;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out29;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out30;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out31;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out32;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out33;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out34;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out35;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out36;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out37;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out38;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out39;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out40;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out41;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out42;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out43;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out44;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out45;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out46;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out47;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out48;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out49;  // sfix15_En5
  wire signed [14:0] Memory_first_data_out50;  // sfix15_En5
  reg [7:0] Counter_Limited2_out1;  // uint8
  reg [7:0] Counter_Limited_out1;  // uint8
  wire signed [36:0] DFT_out1_re;  // sfix37_En22
  wire signed [36:0] DFT_out1_im;  // sfix37_En22
  wire signed [36:0] DFT_out2_re;  // sfix37_En22
  wire signed [36:0] DFT_out2_im;  // sfix37_En22
  wire signed [36:0] DFT_out3_re;  // sfix37_En22
  wire signed [36:0] DFT_out3_im;  // sfix37_En22
  wire signed [36:0] DFT_out4_re;  // sfix37_En22
  wire signed [36:0] DFT_out4_im;  // sfix37_En22
  wire signed [36:0] DFT_out5_re;  // sfix37_En22
  wire signed [36:0] DFT_out5_im;  // sfix37_En22
  wire signed [36:0] DFT_out6_re;  // sfix37_En22
  wire signed [36:0] DFT_out6_im;  // sfix37_En22
  wire signed [36:0] DFT_out7_re;  // sfix37_En22
  wire signed [36:0] DFT_out7_im;  // sfix37_En22
  wire signed [36:0] DFT_out8_re;  // sfix37_En22
  wire signed [36:0] DFT_out8_im;  // sfix37_En22
  wire signed [36:0] DFT_out9_re;  // sfix37_En22
  wire signed [36:0] DFT_out9_im;  // sfix37_En22
  wire signed [36:0] DFT_out10_re;  // sfix37_En22
  wire signed [36:0] DFT_out10_im;  // sfix37_En22
  wire signed [36:0] DFT_out11_re;  // sfix37_En22
  wire signed [36:0] DFT_out11_im;  // sfix37_En22
  wire signed [36:0] DFT_out12_re;  // sfix37_En22
  wire signed [36:0] DFT_out12_im;  // sfix37_En22
  wire signed [36:0] DFT_out13_re;  // sfix37_En22
  wire signed [36:0] DFT_out13_im;  // sfix37_En22
  wire signed [36:0] DFT_out14_re;  // sfix37_En22
  wire signed [36:0] DFT_out14_im;  // sfix37_En22
  wire signed [36:0] DFT_out15_re;  // sfix37_En22
  wire signed [36:0] DFT_out15_im;  // sfix37_En22
  wire signed [36:0] DFT_out16_re;  // sfix37_En22
  wire signed [36:0] DFT_out16_im;  // sfix37_En22
  wire signed [36:0] DFT_out17_re;  // sfix37_En22
  wire signed [36:0] DFT_out17_im;  // sfix37_En22
  wire signed [36:0] DFT_out18_re;  // sfix37_En22
  wire signed [36:0] DFT_out18_im;  // sfix37_En22
  wire signed [36:0] DFT_out19_re;  // sfix37_En22
  wire signed [36:0] DFT_out19_im;  // sfix37_En22
  wire signed [36:0] DFT_out20_re;  // sfix37_En22
  wire signed [36:0] DFT_out20_im;  // sfix37_En22
  wire signed [36:0] DFT_out21_re;  // sfix37_En22
  wire signed [36:0] DFT_out21_im;  // sfix37_En22
  wire signed [36:0] DFT_out22_re;  // sfix37_En22
  wire signed [36:0] DFT_out22_im;  // sfix37_En22
  wire signed [36:0] DFT_out23_re;  // sfix37_En22
  wire signed [36:0] DFT_out23_im;  // sfix37_En22
  wire signed [36:0] DFT_out24_re;  // sfix37_En22
  wire signed [36:0] DFT_out24_im;  // sfix37_En22
  wire signed [36:0] DFT_out25_re;  // sfix37_En22
  wire signed [36:0] DFT_out25_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out1_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out1_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out2_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out2_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out3_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out3_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out4_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out4_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out5_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out5_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out6_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out6_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out7_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out7_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out8_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out8_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out9_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out9_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out10_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out10_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out11_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out11_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out12_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out12_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out13_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out13_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out14_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out14_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out15_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out15_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out16_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out16_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out17_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out17_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out18_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out18_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out19_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out19_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out20_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out20_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out21_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out21_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out22_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out22_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out23_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out23_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out24_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out24_im;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out25_re;  // sfix37_En22
  wire signed [36:0] generating_analytical_spectrum_out25_im;  // sfix37_En22
  wire generating_analytical_spectrum_out26;  // ufix1
  wire signed [36:0] Swapping_out1_re;  // sfix37_En22
  wire signed [36:0] Swapping_out1_im;  // sfix37_En22
  wire signed [36:0] Swapping_out2_re;  // sfix37_En22
  wire signed [36:0] Swapping_out2_im;  // sfix37_En22
  wire signed [36:0] Swapping_out3_re;  // sfix37_En22
  wire signed [36:0] Swapping_out3_im;  // sfix37_En22
  wire signed [36:0] Swapping_out4_re;  // sfix37_En22
  wire signed [36:0] Swapping_out4_im;  // sfix37_En22
  wire signed [36:0] Swapping_out5_re;  // sfix37_En22
  wire signed [36:0] Swapping_out5_im;  // sfix37_En22
  wire signed [36:0] Swapping_out6_re;  // sfix37_En22
  wire signed [36:0] Swapping_out6_im;  // sfix37_En22
  wire signed [36:0] Swapping_out7_re;  // sfix37_En22
  wire signed [36:0] Swapping_out7_im;  // sfix37_En22
  wire signed [36:0] Swapping_out8_re;  // sfix37_En22
  wire signed [36:0] Swapping_out8_im;  // sfix37_En22
  wire signed [36:0] Swapping_out9_re;  // sfix37_En22
  wire signed [36:0] Swapping_out9_im;  // sfix37_En22
  wire signed [36:0] Swapping_out10_re;  // sfix37_En22
  wire signed [36:0] Swapping_out10_im;  // sfix37_En22
  wire signed [36:0] Swapping_out11_re;  // sfix37_En22
  wire signed [36:0] Swapping_out11_im;  // sfix37_En22
  wire signed [36:0] Swapping_out12_re;  // sfix37_En22
  wire signed [36:0] Swapping_out12_im;  // sfix37_En22
  wire signed [36:0] Swapping_out13_re;  // sfix37_En22
  wire signed [36:0] Swapping_out13_im;  // sfix37_En22
  wire signed [36:0] Swapping_out14_re;  // sfix37_En22
  wire signed [36:0] Swapping_out14_im;  // sfix37_En22
  wire signed [36:0] Swapping_out15_re;  // sfix37_En22
  wire signed [36:0] Swapping_out15_im;  // sfix37_En22
  wire signed [36:0] Swapping_out16_re;  // sfix37_En22
  wire signed [36:0] Swapping_out16_im;  // sfix37_En22
  wire signed [36:0] Swapping_out17_re;  // sfix37_En22
  wire signed [36:0] Swapping_out17_im;  // sfix37_En22
  wire signed [36:0] Swapping_out18_re;  // sfix37_En22
  wire signed [36:0] Swapping_out18_im;  // sfix37_En22
  wire signed [36:0] Swapping_out19_re;  // sfix37_En22
  wire signed [36:0] Swapping_out19_im;  // sfix37_En22
  wire signed [36:0] Swapping_out20_re;  // sfix37_En22
  wire signed [36:0] Swapping_out20_im;  // sfix37_En22
  wire signed [36:0] Swapping_out21_re;  // sfix37_En22
  wire signed [36:0] Swapping_out21_im;  // sfix37_En22
  wire signed [36:0] Swapping_out22_re;  // sfix37_En22
  wire signed [36:0] Swapping_out22_im;  // sfix37_En22
  wire signed [36:0] Swapping_out23_re;  // sfix37_En22
  wire signed [36:0] Swapping_out23_im;  // sfix37_En22
  wire signed [36:0] Swapping_out24_re;  // sfix37_En22
  wire signed [36:0] Swapping_out24_im;  // sfix37_En22
  wire signed [36:0] Swapping_out25_re;  // sfix37_En22
  wire signed [36:0] Swapping_out25_im;  // sfix37_En22
  wire Swapping_out26_re;  // ufix1
  wire Swapping_out26_im;  // ufix1
  reg [7:0] Counter_Limited1_out1;  // uint8
  reg [7:0] Counter_Limited3_out1;  // uint8
  wire signed [36:0] DFT_2_out1_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out1_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out2_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out2_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out3_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out3_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out4_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out4_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out5_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out5_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out6_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out6_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out7_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out7_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out8_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out8_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out9_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out9_im;  // sfix37_En22
  wire signed [36:0] DFT_2_out10_re;  // sfix37_En22
  wire signed [36:0] DFT_2_out10_im;  // sfix37_En22
  reg [7:0] Counter_Limited4_out1;  // uint8
  wire signed [14:0] taking_imaginary_part_out1;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out2;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out3;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out4;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out5;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out6;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out7;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out8;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out9;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out10;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out11;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out12;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out13;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out14;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out15;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out16;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out17;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out18;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out19;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out20;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out21;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out22;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out23;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out24;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out25;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out26;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out27;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out28;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out29;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out30;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out31;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out32;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out33;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out34;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out35;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out36;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out37;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out38;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out39;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out40;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out41;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out42;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out43;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out44;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out45;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out46;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out47;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out48;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out49;  // sfix15_En5
  wire signed [14:0] taking_imaginary_part_out50;  // sfix15_En5
  wire signed [14:0] parallel_serial_out1;  // sfix15_En5


  serial_parallel u_serial_parallel (.clk(clk),
                                     .reset_x(reset_x),
                                     .enb(clk_enable),
                                     .In1(in1),  // sfix15_En5
                                     .Out1(serial_parallel_out1),  // sfix15_En5
                                     .Out2(serial_parallel_out2),  // sfix15_En5
                                     .Out3(serial_parallel_out3),  // sfix15_En5
                                     .Out4(serial_parallel_out4),  // sfix15_En5
                                     .Out5(serial_parallel_out5),  // sfix15_En5
                                     .Out6(serial_parallel_out6),  // sfix15_En5
                                     .Out7(serial_parallel_out7),  // sfix15_En5
                                     .Out8(serial_parallel_out8),  // sfix15_En5
                                     .Out9(serial_parallel_out9),  // sfix15_En5
                                     .Out10(serial_parallel_out10),  // sfix15_En5
                                     .Out11(serial_parallel_out11),  // sfix15_En5
                                     .Out12(serial_parallel_out12),  // sfix15_En5
                                     .Out13(serial_parallel_out13),  // sfix15_En5
                                     .Out14(serial_parallel_out14),  // sfix15_En5
                                     .Out15(serial_parallel_out15),  // sfix15_En5
                                     .Out16(serial_parallel_out16),  // sfix15_En5
                                     .Out17(serial_parallel_out17),  // sfix15_En5
                                     .Out18(serial_parallel_out18),  // sfix15_En5
                                     .Out19(serial_parallel_out19),  // sfix15_En5
                                     .Out20(serial_parallel_out20),  // sfix15_En5
                                     .Out21(serial_parallel_out21),  // sfix15_En5
                                     .Out22(serial_parallel_out22),  // sfix15_En5
                                     .Out23(serial_parallel_out23),  // sfix15_En5
                                     .Out24(serial_parallel_out24),  // sfix15_En5
                                     .Out25(serial_parallel_out25),  // sfix15_En5
                                     .Out26(serial_parallel_out26),  // sfix15_En5
                                     .Out27(serial_parallel_out27),  // sfix15_En5
                                     .Out28(serial_parallel_out28),  // sfix15_En5
                                     .Out29(serial_parallel_out29),  // sfix15_En5
                                     .Out30(serial_parallel_out30),  // sfix15_En5
                                     .Out31(serial_parallel_out31),  // sfix15_En5
                                     .Out32(serial_parallel_out32),  // sfix15_En5
                                     .Out33(serial_parallel_out33),  // sfix15_En5
                                     .Out34(serial_parallel_out34),  // sfix15_En5
                                     .Out35(serial_parallel_out35),  // sfix15_En5
                                     .Out36(serial_parallel_out36),  // sfix15_En5
                                     .Out37(serial_parallel_out37),  // sfix15_En5
                                     .Out38(serial_parallel_out38),  // sfix15_En5
                                     .Out39(serial_parallel_out39),  // sfix15_En5
                                     .Out40(serial_parallel_out40),  // sfix15_En5
                                     .Out41(serial_parallel_out41),  // sfix15_En5
                                     .Out42(serial_parallel_out42),  // sfix15_En5
                                     .Out43(serial_parallel_out43),  // sfix15_En5
                                     .Out44(serial_parallel_out44),  // sfix15_En5
                                     .Out45(serial_parallel_out45),  // sfix15_En5
                                     .Out46(serial_parallel_out46),  // sfix15_En5
                                     .Out47(serial_parallel_out47),  // sfix15_En5
                                     .Out48(serial_parallel_out48),  // sfix15_En5
                                     .Out49(serial_parallel_out49),  // sfix15_En5
                                     .Out50(serial_parallel_out50)  // sfix15_En5
                                     );

  Memory_first_data u_Memory_first_data (.clk(clk),
                                         .reset_x(reset_x),
                                         .enb(clk_enable),
                                         .In1(serial_parallel_out1),  // sfix15_En5
                                         .In2(serial_parallel_out2),  // sfix15_En5
                                         .In3(serial_parallel_out3),  // sfix15_En5
                                         .In4(serial_parallel_out4),  // sfix15_En5
                                         .In5(serial_parallel_out5),  // sfix15_En5
                                         .In6(serial_parallel_out6),  // sfix15_En5
                                         .In7(serial_parallel_out7),  // sfix15_En5
                                         .In8(serial_parallel_out8),  // sfix15_En5
                                         .In9(serial_parallel_out9),  // sfix15_En5
                                         .In10(serial_parallel_out10),  // sfix15_En5
                                         .In11(serial_parallel_out11),  // sfix15_En5
                                         .In12(serial_parallel_out12),  // sfix15_En5
                                         .In13(serial_parallel_out13),  // sfix15_En5
                                         .In14(serial_parallel_out14),  // sfix15_En5
                                         .In15(serial_parallel_out15),  // sfix15_En5
                                         .In16(serial_parallel_out16),  // sfix15_En5
                                         .In17(serial_parallel_out17),  // sfix15_En5
                                         .In18(serial_parallel_out18),  // sfix15_En5
                                         .In19(serial_parallel_out19),  // sfix15_En5
                                         .In20(serial_parallel_out20),  // sfix15_En5
                                         .In21(serial_parallel_out21),  // sfix15_En5
                                         .In22(serial_parallel_out22),  // sfix15_En5
                                         .In23(serial_parallel_out23),  // sfix15_En5
                                         .In24(serial_parallel_out24),  // sfix15_En5
                                         .In25(serial_parallel_out25),  // sfix15_En5
                                         .In26(serial_parallel_out26),  // sfix15_En5
                                         .In27(serial_parallel_out27),  // sfix15_En5
                                         .In28(serial_parallel_out28),  // sfix15_En5
                                         .In29(serial_parallel_out29),  // sfix15_En5
                                         .In30(serial_parallel_out30),  // sfix15_En5
                                         .In31(serial_parallel_out31),  // sfix15_En5
                                         .In32(serial_parallel_out32),  // sfix15_En5
                                         .In33(serial_parallel_out33),  // sfix15_En5
                                         .In34(serial_parallel_out34),  // sfix15_En5
                                         .In35(serial_parallel_out35),  // sfix15_En5
                                         .In36(serial_parallel_out36),  // sfix15_En5
                                         .In37(serial_parallel_out37),  // sfix15_En5
                                         .In38(serial_parallel_out38),  // sfix15_En5
                                         .In39(serial_parallel_out39),  // sfix15_En5
                                         .In40(serial_parallel_out40),  // sfix15_En5
                                         .In41(serial_parallel_out41),  // sfix15_En5
                                         .In42(serial_parallel_out42),  // sfix15_En5
                                         .In43(serial_parallel_out43),  // sfix15_En5
                                         .In44(serial_parallel_out44),  // sfix15_En5
                                         .In45(serial_parallel_out45),  // sfix15_En5
                                         .In46(serial_parallel_out46),  // sfix15_En5
                                         .In47(serial_parallel_out47),  // sfix15_En5
                                         .In48(serial_parallel_out48),  // sfix15_En5
                                         .In49(serial_parallel_out49),  // sfix15_En5
                                         .In50(serial_parallel_out50),  // sfix15_En5
                                         .Out1(Memory_first_data_out1),  // sfix15_En5
                                         .Out2(Memory_first_data_out2),  // sfix15_En5
                                         .Out3(Memory_first_data_out3),  // sfix15_En5
                                         .Out4(Memory_first_data_out4),  // sfix15_En5
                                         .Out5(Memory_first_data_out5),  // sfix15_En5
                                         .Out6(Memory_first_data_out6),  // sfix15_En5
                                         .Out7(Memory_first_data_out7),  // sfix15_En5
                                         .Out8(Memory_first_data_out8),  // sfix15_En5
                                         .Out9(Memory_first_data_out9),  // sfix15_En5
                                         .Out10(Memory_first_data_out10),  // sfix15_En5
                                         .Out11(Memory_first_data_out11),  // sfix15_En5
                                         .Out12(Memory_first_data_out12),  // sfix15_En5
                                         .Out13(Memory_first_data_out13),  // sfix15_En5
                                         .Out14(Memory_first_data_out14),  // sfix15_En5
                                         .Out15(Memory_first_data_out15),  // sfix15_En5
                                         .Out16(Memory_first_data_out16),  // sfix15_En5
                                         .Out17(Memory_first_data_out17),  // sfix15_En5
                                         .Out18(Memory_first_data_out18),  // sfix15_En5
                                         .Out19(Memory_first_data_out19),  // sfix15_En5
                                         .Out20(Memory_first_data_out20),  // sfix15_En5
                                         .Out21(Memory_first_data_out21),  // sfix15_En5
                                         .Out22(Memory_first_data_out22),  // sfix15_En5
                                         .Out23(Memory_first_data_out23),  // sfix15_En5
                                         .Out24(Memory_first_data_out24),  // sfix15_En5
                                         .Out25(Memory_first_data_out25),  // sfix15_En5
                                         .Out26(Memory_first_data_out26),  // sfix15_En5
                                         .Out27(Memory_first_data_out27),  // sfix15_En5
                                         .Out28(Memory_first_data_out28),  // sfix15_En5
                                         .Out29(Memory_first_data_out29),  // sfix15_En5
                                         .Out30(Memory_first_data_out30),  // sfix15_En5
                                         .Out31(Memory_first_data_out31),  // sfix15_En5
                                         .Out32(Memory_first_data_out32),  // sfix15_En5
                                         .Out33(Memory_first_data_out33),  // sfix15_En5
                                         .Out34(Memory_first_data_out34),  // sfix15_En5
                                         .Out35(Memory_first_data_out35),  // sfix15_En5
                                         .Out36(Memory_first_data_out36),  // sfix15_En5
                                         .Out37(Memory_first_data_out37),  // sfix15_En5
                                         .Out38(Memory_first_data_out38),  // sfix15_En5
                                         .Out39(Memory_first_data_out39),  // sfix15_En5
                                         .Out40(Memory_first_data_out40),  // sfix15_En5
                                         .Out41(Memory_first_data_out41),  // sfix15_En5
                                         .Out42(Memory_first_data_out42),  // sfix15_En5
                                         .Out43(Memory_first_data_out43),  // sfix15_En5
                                         .Out44(Memory_first_data_out44),  // sfix15_En5
                                         .Out45(Memory_first_data_out45),  // sfix15_En5
                                         .Out46(Memory_first_data_out46),  // sfix15_En5
                                         .Out47(Memory_first_data_out47),  // sfix15_En5
                                         .Out48(Memory_first_data_out48),  // sfix15_En5
                                         .Out49(Memory_first_data_out49),  // sfix15_En5
                                         .Out50(Memory_first_data_out50)  // sfix15_En5
                                         );

  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  always @(posedge clk)
    begin : Counter_Limited2_process
      if (reset_x == 1'b1) begin
        Counter_Limited2_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Counter_Limited2_out1 >= 8'b00001010) begin
            Counter_Limited2_out1 <= 8'b00000000;
          end
          else begin
            Counter_Limited2_out1 <= Counter_Limited2_out1 + 8'b00000001;
          end
        end
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5
  always @(posedge clk)
    begin : Counter_Limited_process
      if (reset_x == 1'b1) begin
        Counter_Limited_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Counter_Limited_out1 >= 8'b00000101) begin
            Counter_Limited_out1 <= 8'b00000000;
          end
          else begin
            Counter_Limited_out1 <= Counter_Limited_out1 + 8'b00000001;
          end
        end
      end
    end



  DFT u_DFT (.clk(clk),
             .reset_x(reset_x),
             .enb(clk_enable),
             .In1(Memory_first_data_out1),  // sfix15_En5
             .In2(Memory_first_data_out2),  // sfix15_En5
             .In3(Memory_first_data_out3),  // sfix15_En5
             .In4(Memory_first_data_out4),  // sfix15_En5
             .In5(Memory_first_data_out5),  // sfix15_En5
             .In6(Memory_first_data_out6),  // sfix15_En5
             .In7(Memory_first_data_out7),  // sfix15_En5
             .In8(Memory_first_data_out8),  // sfix15_En5
             .In9(Memory_first_data_out9),  // sfix15_En5
             .In10(Memory_first_data_out10),  // sfix15_En5
             .In11(Memory_first_data_out11),  // sfix15_En5
             .In12(Memory_first_data_out12),  // sfix15_En5
             .In13(Memory_first_data_out13),  // sfix15_En5
             .In14(Memory_first_data_out14),  // sfix15_En5
             .In15(Memory_first_data_out15),  // sfix15_En5
             .In16(Memory_first_data_out16),  // sfix15_En5
             .In17(Memory_first_data_out17),  // sfix15_En5
             .In18(Memory_first_data_out18),  // sfix15_En5
             .In19(Memory_first_data_out19),  // sfix15_En5
             .In20(Memory_first_data_out20),  // sfix15_En5
             .In21(Memory_first_data_out21),  // sfix15_En5
             .In22(Memory_first_data_out22),  // sfix15_En5
             .In23(Memory_first_data_out23),  // sfix15_En5
             .In24(Memory_first_data_out24),  // sfix15_En5
             .In25(Memory_first_data_out25),  // sfix15_En5
             .In26(Memory_first_data_out26),  // sfix15_En5
             .In27(Memory_first_data_out27),  // sfix15_En5
             .In28(Memory_first_data_out28),  // sfix15_En5
             .In29(Memory_first_data_out29),  // sfix15_En5
             .In30(Memory_first_data_out30),  // sfix15_En5
             .In31(Memory_first_data_out31),  // sfix15_En5
             .In32(Memory_first_data_out32),  // sfix15_En5
             .In33(Memory_first_data_out33),  // sfix15_En5
             .In34(Memory_first_data_out34),  // sfix15_En5
             .In35(Memory_first_data_out35),  // sfix15_En5
             .In36(Memory_first_data_out36),  // sfix15_En5
             .In37(Memory_first_data_out37),  // sfix15_En5
             .In38(Memory_first_data_out38),  // sfix15_En5
             .In39(Memory_first_data_out39),  // sfix15_En5
             .In40(Memory_first_data_out40),  // sfix15_En5
             .In41(Memory_first_data_out41),  // sfix15_En5
             .In42(Memory_first_data_out42),  // sfix15_En5
             .In43(Memory_first_data_out43),  // sfix15_En5
             .In44(Memory_first_data_out44),  // sfix15_En5
             .In45(Memory_first_data_out45),  // sfix15_En5
             .In46(Memory_first_data_out46),  // sfix15_En5
             .In47(Memory_first_data_out47),  // sfix15_En5
             .In48(Memory_first_data_out48),  // sfix15_En5
             .In49(Memory_first_data_out49),  // sfix15_En5
             .In50(Memory_first_data_out50),  // sfix15_En5
             .In51(Counter_Limited2_out1),  // uint8
             .In52(Counter_Limited2_out1),  // uint8
             .In53(Counter_Limited_out1),  // uint8
             .Out1_re(DFT_out1_re),  // sfix37_En22
             .Out1_im(DFT_out1_im),  // sfix37_En22
             .Out2_re(DFT_out2_re),  // sfix37_En22
             .Out2_im(DFT_out2_im),  // sfix37_En22
             .Out3_re(DFT_out3_re),  // sfix37_En22
             .Out3_im(DFT_out3_im),  // sfix37_En22
             .Out4_re(DFT_out4_re),  // sfix37_En22
             .Out4_im(DFT_out4_im),  // sfix37_En22
             .Out5_re(DFT_out5_re),  // sfix37_En22
             .Out5_im(DFT_out5_im),  // sfix37_En22
             .Out6_re(DFT_out6_re),  // sfix37_En22
             .Out6_im(DFT_out6_im),  // sfix37_En22
             .Out7_re(DFT_out7_re),  // sfix37_En22
             .Out7_im(DFT_out7_im),  // sfix37_En22
             .Out8_re(DFT_out8_re),  // sfix37_En22
             .Out8_im(DFT_out8_im),  // sfix37_En22
             .Out9_re(DFT_out9_re),  // sfix37_En22
             .Out9_im(DFT_out9_im),  // sfix37_En22
             .Out10_re(DFT_out10_re),  // sfix37_En22
             .Out10_im(DFT_out10_im),  // sfix37_En22
             .Out11_re(DFT_out11_re),  // sfix37_En22
             .Out11_im(DFT_out11_im),  // sfix37_En22
             .Out12_re(DFT_out12_re),  // sfix37_En22
             .Out12_im(DFT_out12_im),  // sfix37_En22
             .Out13_re(DFT_out13_re),  // sfix37_En22
             .Out13_im(DFT_out13_im),  // sfix37_En22
             .Out14_re(DFT_out14_re),  // sfix37_En22
             .Out14_im(DFT_out14_im),  // sfix37_En22
             .Out15_re(DFT_out15_re),  // sfix37_En22
             .Out15_im(DFT_out15_im),  // sfix37_En22
             .Out16_re(DFT_out16_re),  // sfix37_En22
             .Out16_im(DFT_out16_im),  // sfix37_En22
             .Out17_re(DFT_out17_re),  // sfix37_En22
             .Out17_im(DFT_out17_im),  // sfix37_En22
             .Out18_re(DFT_out18_re),  // sfix37_En22
             .Out18_im(DFT_out18_im),  // sfix37_En22
             .Out19_re(DFT_out19_re),  // sfix37_En22
             .Out19_im(DFT_out19_im),  // sfix37_En22
             .Out20_re(DFT_out20_re),  // sfix37_En22
             .Out20_im(DFT_out20_im),  // sfix37_En22
             .Out21_re(DFT_out21_re),  // sfix37_En22
             .Out21_im(DFT_out21_im),  // sfix37_En22
             .Out22_re(DFT_out22_re),  // sfix37_En22
             .Out22_im(DFT_out22_im),  // sfix37_En22
             .Out23_re(DFT_out23_re),  // sfix37_En22
             .Out23_im(DFT_out23_im),  // sfix37_En22
             .Out24_re(DFT_out24_re),  // sfix37_En22
             .Out24_im(DFT_out24_im),  // sfix37_En22
             .Out25_re(DFT_out25_re),  // sfix37_En22
             .Out25_im(DFT_out25_im)  // sfix37_En22
             );

  generating_analytical_spectrum u_generating_analytical_spectrum (.clk(clk),
                                                                   .reset_x(reset_x),
                                                                   .enb(clk_enable),
                                                                   .X_0_re(DFT_out1_re),  // sfix37_En22
                                                                   .X_0_im(DFT_out1_im),  // sfix37_En22
                                                                   .X_1_re(DFT_out2_re),  // sfix37_En22
                                                                   .X_1_im(DFT_out2_im),  // sfix37_En22
                                                                   .X_2_re(DFT_out3_re),  // sfix37_En22
                                                                   .X_2_im(DFT_out3_im),  // sfix37_En22
                                                                   .X_3_re(DFT_out4_re),  // sfix37_En22
                                                                   .X_3_im(DFT_out4_im),  // sfix37_En22
                                                                   .X_4_re(DFT_out5_re),  // sfix37_En22
                                                                   .X_4_im(DFT_out5_im),  // sfix37_En22
                                                                   .X_5_re(DFT_out6_re),  // sfix37_En22
                                                                   .X_5_im(DFT_out6_im),  // sfix37_En22
                                                                   .X_6_re(DFT_out7_re),  // sfix37_En22
                                                                   .X_6_im(DFT_out7_im),  // sfix37_En22
                                                                   .X_7_re(DFT_out8_re),  // sfix37_En22
                                                                   .X_7_im(DFT_out8_im),  // sfix37_En22
                                                                   .X_8_re(DFT_out9_re),  // sfix37_En22
                                                                   .X_8_im(DFT_out9_im),  // sfix37_En22
                                                                   .X_9_re(DFT_out10_re),  // sfix37_En22
                                                                   .X_9_im(DFT_out10_im),  // sfix37_En22
                                                                   .X_10_re(DFT_out11_re),  // sfix37_En22
                                                                   .X_10_im(DFT_out11_im),  // sfix37_En22
                                                                   .X_11_re(DFT_out12_re),  // sfix37_En22
                                                                   .X_11_im(DFT_out12_im),  // sfix37_En22
                                                                   .X_12_re(DFT_out13_re),  // sfix37_En22
                                                                   .X_12_im(DFT_out13_im),  // sfix37_En22
                                                                   .X_13_re(DFT_out14_re),  // sfix37_En22
                                                                   .X_13_im(DFT_out14_im),  // sfix37_En22
                                                                   .X_14_re(DFT_out15_re),  // sfix37_En22
                                                                   .X_14_im(DFT_out15_im),  // sfix37_En22
                                                                   .X_15_re(DFT_out16_re),  // sfix37_En22
                                                                   .X_15_im(DFT_out16_im),  // sfix37_En22
                                                                   .X_16_re(DFT_out17_re),  // sfix37_En22
                                                                   .X_16_im(DFT_out17_im),  // sfix37_En22
                                                                   .X_17_re(DFT_out18_re),  // sfix37_En22
                                                                   .X_17_im(DFT_out18_im),  // sfix37_En22
                                                                   .X_18_re(DFT_out19_re),  // sfix37_En22
                                                                   .X_18_im(DFT_out19_im),  // sfix37_En22
                                                                   .X_19_re(DFT_out20_re),  // sfix37_En22
                                                                   .X_19_im(DFT_out20_im),  // sfix37_En22
                                                                   .X_20_re(DFT_out21_re),  // sfix37_En22
                                                                   .X_20_im(DFT_out21_im),  // sfix37_En22
                                                                   .X_21_re(DFT_out22_re),  // sfix37_En22
                                                                   .X_21_im(DFT_out22_im),  // sfix37_En22
                                                                   .X_22_re(DFT_out23_re),  // sfix37_En22
                                                                   .X_22_im(DFT_out23_im),  // sfix37_En22
                                                                   .X_23_re(DFT_out24_re),  // sfix37_En22
                                                                   .X_23_im(DFT_out24_im),  // sfix37_En22
                                                                   .X_24_re(DFT_out25_re),  // sfix37_En22
                                                                   .X_24_im(DFT_out25_im),  // sfix37_En22
                                                                   .Xc_0_re(generating_analytical_spectrum_out1_re),  // sfix37_En22
                                                                   .Xc_0_im(generating_analytical_spectrum_out1_im),  // sfix37_En22
                                                                   .Xc_1_re(generating_analytical_spectrum_out2_re),  // sfix37_En22
                                                                   .Xc_1_im(generating_analytical_spectrum_out2_im),  // sfix37_En22
                                                                   .Xc_2_re(generating_analytical_spectrum_out3_re),  // sfix37_En22
                                                                   .Xc_2_im(generating_analytical_spectrum_out3_im),  // sfix37_En22
                                                                   .Xc_3_re(generating_analytical_spectrum_out4_re),  // sfix37_En22
                                                                   .Xc_3_im(generating_analytical_spectrum_out4_im),  // sfix37_En22
                                                                   .Xc_4_re(generating_analytical_spectrum_out5_re),  // sfix37_En22
                                                                   .Xc_4_im(generating_analytical_spectrum_out5_im),  // sfix37_En22
                                                                   .Xc_5_re(generating_analytical_spectrum_out6_re),  // sfix37_En22
                                                                   .Xc_5_im(generating_analytical_spectrum_out6_im),  // sfix37_En22
                                                                   .Xc_6_re(generating_analytical_spectrum_out7_re),  // sfix37_En22
                                                                   .Xc_6_im(generating_analytical_spectrum_out7_im),  // sfix37_En22
                                                                   .Xc_7_re(generating_analytical_spectrum_out8_re),  // sfix37_En22
                                                                   .Xc_7_im(generating_analytical_spectrum_out8_im),  // sfix37_En22
                                                                   .Xc_8_re(generating_analytical_spectrum_out9_re),  // sfix37_En22
                                                                   .Xc_8_im(generating_analytical_spectrum_out9_im),  // sfix37_En22
                                                                   .Xc_9_re(generating_analytical_spectrum_out10_re),  // sfix37_En22
                                                                   .Xc_9_im(generating_analytical_spectrum_out10_im),  // sfix37_En22
                                                                   .Xc_10_re(generating_analytical_spectrum_out11_re),  // sfix37_En22
                                                                   .Xc_10_im(generating_analytical_spectrum_out11_im),  // sfix37_En22
                                                                   .Xc_11_re(generating_analytical_spectrum_out12_re),  // sfix37_En22
                                                                   .Xc_11_im(generating_analytical_spectrum_out12_im),  // sfix37_En22
                                                                   .Xc_12_re(generating_analytical_spectrum_out13_re),  // sfix37_En22
                                                                   .Xc_12_im(generating_analytical_spectrum_out13_im),  // sfix37_En22
                                                                   .Xc_13_re(generating_analytical_spectrum_out14_re),  // sfix37_En22
                                                                   .Xc_13_im(generating_analytical_spectrum_out14_im),  // sfix37_En22
                                                                   .Xc_14_re(generating_analytical_spectrum_out15_re),  // sfix37_En22
                                                                   .Xc_14_im(generating_analytical_spectrum_out15_im),  // sfix37_En22
                                                                   .Xc_15_re(generating_analytical_spectrum_out16_re),  // sfix37_En22
                                                                   .Xc_15_im(generating_analytical_spectrum_out16_im),  // sfix37_En22
                                                                   .Xc_16_re(generating_analytical_spectrum_out17_re),  // sfix37_En22
                                                                   .Xc_16_im(generating_analytical_spectrum_out17_im),  // sfix37_En22
                                                                   .Xc_17_re(generating_analytical_spectrum_out18_re),  // sfix37_En22
                                                                   .Xc_17_im(generating_analytical_spectrum_out18_im),  // sfix37_En22
                                                                   .Xc_18_re(generating_analytical_spectrum_out19_re),  // sfix37_En22
                                                                   .Xc_18_im(generating_analytical_spectrum_out19_im),  // sfix37_En22
                                                                   .Xc_19_re(generating_analytical_spectrum_out20_re),  // sfix37_En22
                                                                   .Xc_19_im(generating_analytical_spectrum_out20_im),  // sfix37_En22
                                                                   .Xc_20_re(generating_analytical_spectrum_out21_re),  // sfix37_En22
                                                                   .Xc_20_im(generating_analytical_spectrum_out21_im),  // sfix37_En22
                                                                   .Xc_21_re(generating_analytical_spectrum_out22_re),  // sfix37_En22
                                                                   .Xc_21_im(generating_analytical_spectrum_out22_im),  // sfix37_En22
                                                                   .Xc_22_re(generating_analytical_spectrum_out23_re),  // sfix37_En22
                                                                   .Xc_22_im(generating_analytical_spectrum_out23_im),  // sfix37_En22
                                                                   .Xc_23_re(generating_analytical_spectrum_out24_re),  // sfix37_En22
                                                                   .Xc_23_im(generating_analytical_spectrum_out24_im),  // sfix37_En22
                                                                   .Xc_24_re(generating_analytical_spectrum_out25_re),  // sfix37_En22
                                                                   .Xc_24_im(generating_analytical_spectrum_out25_im),  // sfix37_En22
                                                                   .Xc_0_1(generating_analytical_spectrum_out26)  // ufix1
                                                                   );

  Swapping u_Swapping (.Xc_0_re(generating_analytical_spectrum_out1_re),  // sfix37_En22
                       .Xc_0_im(generating_analytical_spectrum_out1_im),  // sfix37_En22
                       .Xc_1_re(generating_analytical_spectrum_out2_re),  // sfix37_En22
                       .Xc_1_im(generating_analytical_spectrum_out2_im),  // sfix37_En22
                       .Xc_2_re(generating_analytical_spectrum_out3_re),  // sfix37_En22
                       .Xc_2_im(generating_analytical_spectrum_out3_im),  // sfix37_En22
                       .Xc_3_re(generating_analytical_spectrum_out4_re),  // sfix37_En22
                       .Xc_3_im(generating_analytical_spectrum_out4_im),  // sfix37_En22
                       .Xc_4_re(generating_analytical_spectrum_out5_re),  // sfix37_En22
                       .Xc_4_im(generating_analytical_spectrum_out5_im),  // sfix37_En22
                       .Xc_5_re(generating_analytical_spectrum_out6_re),  // sfix37_En22
                       .Xc_5_im(generating_analytical_spectrum_out6_im),  // sfix37_En22
                       .Xc_6_re(generating_analytical_spectrum_out7_re),  // sfix37_En22
                       .Xc_6_im(generating_analytical_spectrum_out7_im),  // sfix37_En22
                       .Xc_7_re(generating_analytical_spectrum_out8_re),  // sfix37_En22
                       .Xc_7_im(generating_analytical_spectrum_out8_im),  // sfix37_En22
                       .Xc_8_re(generating_analytical_spectrum_out9_re),  // sfix37_En22
                       .Xc_8_im(generating_analytical_spectrum_out9_im),  // sfix37_En22
                       .Xc_9_re(generating_analytical_spectrum_out10_re),  // sfix37_En22
                       .Xc_9_im(generating_analytical_spectrum_out10_im),  // sfix37_En22
                       .Xc_10_re(generating_analytical_spectrum_out11_re),  // sfix37_En22
                       .Xc_10_im(generating_analytical_spectrum_out11_im),  // sfix37_En22
                       .Xc_11_re(generating_analytical_spectrum_out12_re),  // sfix37_En22
                       .Xc_11_im(generating_analytical_spectrum_out12_im),  // sfix37_En22
                       .Xc_12_re(generating_analytical_spectrum_out13_re),  // sfix37_En22
                       .Xc_12_im(generating_analytical_spectrum_out13_im),  // sfix37_En22
                       .Xc_13_re(generating_analytical_spectrum_out14_re),  // sfix37_En22
                       .Xc_13_im(generating_analytical_spectrum_out14_im),  // sfix37_En22
                       .Xc_14_re(generating_analytical_spectrum_out15_re),  // sfix37_En22
                       .Xc_14_im(generating_analytical_spectrum_out15_im),  // sfix37_En22
                       .Xc_15_re(generating_analytical_spectrum_out16_re),  // sfix37_En22
                       .Xc_15_im(generating_analytical_spectrum_out16_im),  // sfix37_En22
                       .Xc_16_re(generating_analytical_spectrum_out17_re),  // sfix37_En22
                       .Xc_16_im(generating_analytical_spectrum_out17_im),  // sfix37_En22
                       .Xc_17_re(generating_analytical_spectrum_out18_re),  // sfix37_En22
                       .Xc_17_im(generating_analytical_spectrum_out18_im),  // sfix37_En22
                       .Xc_18_re(generating_analytical_spectrum_out19_re),  // sfix37_En22
                       .Xc_18_im(generating_analytical_spectrum_out19_im),  // sfix37_En22
                       .Xc_19_re(generating_analytical_spectrum_out20_re),  // sfix37_En22
                       .Xc_19_im(generating_analytical_spectrum_out20_im),  // sfix37_En22
                       .Xc_20_re(generating_analytical_spectrum_out21_re),  // sfix37_En22
                       .Xc_20_im(generating_analytical_spectrum_out21_im),  // sfix37_En22
                       .Xc_21_re(generating_analytical_spectrum_out22_re),  // sfix37_En22
                       .Xc_21_im(generating_analytical_spectrum_out22_im),  // sfix37_En22
                       .Xc_22_re(generating_analytical_spectrum_out23_re),  // sfix37_En22
                       .Xc_22_im(generating_analytical_spectrum_out23_im),  // sfix37_En22
                       .Xc_23_re(generating_analytical_spectrum_out24_re),  // sfix37_En22
                       .Xc_23_im(generating_analytical_spectrum_out24_im),  // sfix37_En22
                       .Xc_24_re(generating_analytical_spectrum_out25_re),  // sfix37_En22
                       .Xc_24_im(generating_analytical_spectrum_out25_im),  // sfix37_En22
                       .Xc_25(generating_analytical_spectrum_out26),  // ufix1
                       .Xs_0_re(Swapping_out1_re),  // sfix37_En22
                       .Xs_0_im(Swapping_out1_im),  // sfix37_En22
                       .Xs_1_re(Swapping_out2_re),  // sfix37_En22
                       .Xs_1_im(Swapping_out2_im),  // sfix37_En22
                       .Xs_2_re(Swapping_out3_re),  // sfix37_En22
                       .Xs_2_im(Swapping_out3_im),  // sfix37_En22
                       .Xs_3_re(Swapping_out4_re),  // sfix37_En22
                       .Xs_3_im(Swapping_out4_im),  // sfix37_En22
                       .Xs_4_re(Swapping_out5_re),  // sfix37_En22
                       .Xs_4_im(Swapping_out5_im),  // sfix37_En22
                       .Xs_5_re(Swapping_out6_re),  // sfix37_En22
                       .Xs_5_im(Swapping_out6_im),  // sfix37_En22
                       .Xs_6_re(Swapping_out7_re),  // sfix37_En22
                       .Xs_6_im(Swapping_out7_im),  // sfix37_En22
                       .Xs_7_re(Swapping_out8_re),  // sfix37_En22
                       .Xs_7_im(Swapping_out8_im),  // sfix37_En22
                       .Xs_8_re(Swapping_out9_re),  // sfix37_En22
                       .Xs_8_im(Swapping_out9_im),  // sfix37_En22
                       .Xs_9_re(Swapping_out10_re),  // sfix37_En22
                       .Xs_9_im(Swapping_out10_im),  // sfix37_En22
                       .Xs_10_re(Swapping_out11_re),  // sfix37_En22
                       .Xs_10_im(Swapping_out11_im),  // sfix37_En22
                       .Xs_11_re(Swapping_out12_re),  // sfix37_En22
                       .Xs_11_im(Swapping_out12_im),  // sfix37_En22
                       .Xs_12_re(Swapping_out13_re),  // sfix37_En22
                       .Xs_12_im(Swapping_out13_im),  // sfix37_En22
                       .Xs_13_re(Swapping_out14_re),  // sfix37_En22
                       .Xs_13_im(Swapping_out14_im),  // sfix37_En22
                       .Xs_14_re(Swapping_out15_re),  // sfix37_En22
                       .Xs_14_im(Swapping_out15_im),  // sfix37_En22
                       .Xs_15_re(Swapping_out16_re),  // sfix37_En22
                       .Xs_15_im(Swapping_out16_im),  // sfix37_En22
                       .Xs_16_re(Swapping_out17_re),  // sfix37_En22
                       .Xs_16_im(Swapping_out17_im),  // sfix37_En22
                       .Xs_17_re(Swapping_out18_re),  // sfix37_En22
                       .Xs_17_im(Swapping_out18_im),  // sfix37_En22
                       .Xs_18_re(Swapping_out19_re),  // sfix37_En22
                       .Xs_18_im(Swapping_out19_im),  // sfix37_En22
                       .Xs_19_re(Swapping_out20_re),  // sfix37_En22
                       .Xs_19_im(Swapping_out20_im),  // sfix37_En22
                       .Xs_20_re(Swapping_out21_re),  // sfix37_En22
                       .Xs_20_im(Swapping_out21_im),  // sfix37_En22
                       .Xs_21_re(Swapping_out22_re),  // sfix37_En22
                       .Xs_21_im(Swapping_out22_im),  // sfix37_En22
                       .Xs_22_re(Swapping_out23_re),  // sfix37_En22
                       .Xs_22_im(Swapping_out23_im),  // sfix37_En22
                       .Xs_23_re(Swapping_out24_re),  // sfix37_En22
                       .Xs_23_im(Swapping_out24_im),  // sfix37_En22
                       .Xs_24_re(Swapping_out25_re),  // sfix37_En22
                       .Xs_24_im(Swapping_out25_im),  // sfix37_En22
                       .Xs_25_re(Swapping_out26_re),  // ufix1
                       .Xs_25_im(Swapping_out26_im)  // ufix1
                       );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 14
  always @(posedge clk)
    begin : Counter_Limited1_process
      if (reset_x == 1'b1) begin
        Counter_Limited1_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Counter_Limited1_out1 >= 8'b00001110) begin
            Counter_Limited1_out1 <= 8'b00000000;
          end
          else begin
            Counter_Limited1_out1 <= Counter_Limited1_out1 + 8'b00000001;
          end
        end
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 19
  always @(posedge clk)
    begin : Counter_Limited3_process
      if (reset_x == 1'b1) begin
        Counter_Limited3_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Counter_Limited3_out1 >= 8'b00010011) begin
            Counter_Limited3_out1 <= 8'b00000000;
          end
          else begin
            Counter_Limited3_out1 <= Counter_Limited3_out1 + 8'b00000001;
          end
        end
      end
    end



  DFT_2 u_DFT_2 (.clk(clk),
                 .reset_x(reset_x),
                 .enb(clk_enable),
                 .In1_re(Swapping_out1_re),  // sfix37_En22
                 .In1_im(Swapping_out1_im),  // sfix37_En22
                 .In2_re(Swapping_out2_re),  // sfix37_En22
                 .In2_im(Swapping_out2_im),  // sfix37_En22
                 .In3_re(Swapping_out3_re),  // sfix37_En22
                 .In3_im(Swapping_out3_im),  // sfix37_En22
                 .In4_re(Swapping_out4_re),  // sfix37_En22
                 .In4_im(Swapping_out4_im),  // sfix37_En22
                 .In5_re(Swapping_out5_re),  // sfix37_En22
                 .In5_im(Swapping_out5_im),  // sfix37_En22
                 .In6_re(Swapping_out6_re),  // sfix37_En22
                 .In6_im(Swapping_out6_im),  // sfix37_En22
                 .In7_re(Swapping_out7_re),  // sfix37_En22
                 .In7_im(Swapping_out7_im),  // sfix37_En22
                 .In8_re(Swapping_out8_re),  // sfix37_En22
                 .In8_im(Swapping_out8_im),  // sfix37_En22
                 .In9_re(Swapping_out9_re),  // sfix37_En22
                 .In9_im(Swapping_out9_im),  // sfix37_En22
                 .In10_re(Swapping_out10_re),  // sfix37_En22
                 .In10_im(Swapping_out10_im),  // sfix37_En22
                 .In11_re(Swapping_out11_re),  // sfix37_En22
                 .In11_im(Swapping_out11_im),  // sfix37_En22
                 .In12_re(Swapping_out12_re),  // sfix37_En22
                 .In12_im(Swapping_out12_im),  // sfix37_En22
                 .In13_re(Swapping_out13_re),  // sfix37_En22
                 .In13_im(Swapping_out13_im),  // sfix37_En22
                 .In14_re(Swapping_out14_re),  // sfix37_En22
                 .In14_im(Swapping_out14_im),  // sfix37_En22
                 .In15_re(Swapping_out15_re),  // sfix37_En22
                 .In15_im(Swapping_out15_im),  // sfix37_En22
                 .In16_re(Swapping_out16_re),  // sfix37_En22
                 .In16_im(Swapping_out16_im),  // sfix37_En22
                 .In17_re(Swapping_out17_re),  // sfix37_En22
                 .In17_im(Swapping_out17_im),  // sfix37_En22
                 .In18_re(Swapping_out18_re),  // sfix37_En22
                 .In18_im(Swapping_out18_im),  // sfix37_En22
                 .In19_re(Swapping_out19_re),  // sfix37_En22
                 .In19_im(Swapping_out19_im),  // sfix37_En22
                 .In20_re(Swapping_out20_re),  // sfix37_En22
                 .In20_im(Swapping_out20_im),  // sfix37_En22
                 .In21_re(Swapping_out21_re),  // sfix37_En22
                 .In21_im(Swapping_out21_im),  // sfix37_En22
                 .In22_re(Swapping_out22_re),  // sfix37_En22
                 .In22_im(Swapping_out22_im),  // sfix37_En22
                 .In23_re(Swapping_out23_re),  // sfix37_En22
                 .In23_im(Swapping_out23_im),  // sfix37_En22
                 .In24_re(Swapping_out24_re),  // sfix37_En22
                 .In24_im(Swapping_out24_im),  // sfix37_En22
                 .In25_re(Swapping_out25_re),  // sfix37_En22
                 .In25_im(Swapping_out25_im),  // sfix37_En22
                 .x10_1_4_re(Swapping_out26_re),  // ufix1
                 .x10_1_4_im(Swapping_out26_im),  // ufix1
                 .In27(Counter_Limited1_out1),  // uint8
                 .In28(Counter_Limited3_out1),  // uint8
                 .In29(Counter_Limited2_out1),  // uint8
                 .Out1_re(DFT_2_out1_re),  // sfix37_En22
                 .Out1_im(DFT_2_out1_im),  // sfix37_En22
                 .Out2_re(DFT_2_out2_re),  // sfix37_En22
                 .Out2_im(DFT_2_out2_im),  // sfix37_En22
                 .Out3_re(DFT_2_out3_re),  // sfix37_En22
                 .Out3_im(DFT_2_out3_im),  // sfix37_En22
                 .Out4_re(DFT_2_out4_re),  // sfix37_En22
                 .Out4_im(DFT_2_out4_im),  // sfix37_En22
                 .Out5_re(DFT_2_out5_re),  // sfix37_En22
                 .Out5_im(DFT_2_out5_im),  // sfix37_En22
                 .Out6_re(DFT_2_out6_re),  // sfix37_En22
                 .Out6_im(DFT_2_out6_im),  // sfix37_En22
                 .Out7_re(DFT_2_out7_re),  // sfix37_En22
                 .Out7_im(DFT_2_out7_im),  // sfix37_En22
                 .Out8_re(DFT_2_out8_re),  // sfix37_En22
                 .Out8_im(DFT_2_out8_im),  // sfix37_En22
                 .Out9_re(DFT_2_out9_re),  // sfix37_En22
                 .Out9_im(DFT_2_out9_im),  // sfix37_En22
                 .Out10_re(DFT_2_out10_re),  // sfix37_En22
                 .Out10_im(DFT_2_out10_im)  // sfix37_En22
                 );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 49
  always @(posedge clk)
    begin : Counter_Limited4_process
      if (reset_x == 1'b1) begin
        Counter_Limited4_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Counter_Limited4_out1 >= 8'b00110001) begin
            Counter_Limited4_out1 <= 8'b00000000;
          end
          else begin
            Counter_Limited4_out1 <= Counter_Limited4_out1 + 8'b00000001;
          end
        end
      end
    end



  taking_imaginary_part u_taking_imaginary_part (.clk(clk),
                                                 .reset_x(reset_x),
                                                 .enb(clk_enable),
                                                 .In1_re(DFT_2_out1_re),  // sfix37_En22
                                                 .In2_re(DFT_2_out2_re),  // sfix37_En22
                                                 .In3_re(DFT_2_out3_re),  // sfix37_En22
                                                 .In4_re(DFT_2_out4_re),  // sfix37_En22
                                                 .In5_re(DFT_2_out5_re),  // sfix37_En22
                                                 .In6_re(DFT_2_out6_re),  // sfix37_En22
                                                 .In7_re(DFT_2_out7_re),  // sfix37_En22
                                                 .In8_re(DFT_2_out8_re),  // sfix37_En22
                                                 .In9_re(DFT_2_out9_re),  // sfix37_En22
                                                 .In10_re(DFT_2_out10_re),  // sfix37_En22
                                                 .In11(Counter_Limited4_out1),  // uint8
                                                 .Out1(taking_imaginary_part_out1),  // sfix15_En5
                                                 .Out2(taking_imaginary_part_out2),  // sfix15_En5
                                                 .Out3(taking_imaginary_part_out3),  // sfix15_En5
                                                 .Out4(taking_imaginary_part_out4),  // sfix15_En5
                                                 .Out5(taking_imaginary_part_out5),  // sfix15_En5
                                                 .Out6(taking_imaginary_part_out6),  // sfix15_En5
                                                 .Out7(taking_imaginary_part_out7),  // sfix15_En5
                                                 .Out8(taking_imaginary_part_out8),  // sfix15_En5
                                                 .Out9(taking_imaginary_part_out9),  // sfix15_En5
                                                 .Out10(taking_imaginary_part_out10),  // sfix15_En5
                                                 .Out11(taking_imaginary_part_out11),  // sfix15_En5
                                                 .Out12(taking_imaginary_part_out12),  // sfix15_En5
                                                 .Out13(taking_imaginary_part_out13),  // sfix15_En5
                                                 .Out14(taking_imaginary_part_out14),  // sfix15_En5
                                                 .Out15(taking_imaginary_part_out15),  // sfix15_En5
                                                 .Out16(taking_imaginary_part_out16),  // sfix15_En5
                                                 .Out17(taking_imaginary_part_out17),  // sfix15_En5
                                                 .Out18(taking_imaginary_part_out18),  // sfix15_En5
                                                 .Out19(taking_imaginary_part_out19),  // sfix15_En5
                                                 .Out20(taking_imaginary_part_out20),  // sfix15_En5
                                                 .Out21(taking_imaginary_part_out21),  // sfix15_En5
                                                 .Out22(taking_imaginary_part_out22),  // sfix15_En5
                                                 .Out23(taking_imaginary_part_out23),  // sfix15_En5
                                                 .Out24(taking_imaginary_part_out24),  // sfix15_En5
                                                 .Out25(taking_imaginary_part_out25),  // sfix15_En5
                                                 .Out26(taking_imaginary_part_out26),  // sfix15_En5
                                                 .Out27(taking_imaginary_part_out27),  // sfix15_En5
                                                 .Out28(taking_imaginary_part_out28),  // sfix15_En5
                                                 .Out29(taking_imaginary_part_out29),  // sfix15_En5
                                                 .Out30(taking_imaginary_part_out30),  // sfix15_En5
                                                 .Out31(taking_imaginary_part_out31),  // sfix15_En5
                                                 .Out32(taking_imaginary_part_out32),  // sfix15_En5
                                                 .Out33(taking_imaginary_part_out33),  // sfix15_En5
                                                 .Out34(taking_imaginary_part_out34),  // sfix15_En5
                                                 .Out35(taking_imaginary_part_out35),  // sfix15_En5
                                                 .Out36(taking_imaginary_part_out36),  // sfix15_En5
                                                 .Out37(taking_imaginary_part_out37),  // sfix15_En5
                                                 .Out38(taking_imaginary_part_out38),  // sfix15_En5
                                                 .Out39(taking_imaginary_part_out39),  // sfix15_En5
                                                 .Out40(taking_imaginary_part_out40),  // sfix15_En5
                                                 .Out41(taking_imaginary_part_out41),  // sfix15_En5
                                                 .Out42(taking_imaginary_part_out42),  // sfix15_En5
                                                 .Out43(taking_imaginary_part_out43),  // sfix15_En5
                                                 .Out44(taking_imaginary_part_out44),  // sfix15_En5
                                                 .Out45(taking_imaginary_part_out45),  // sfix15_En5
                                                 .Out46(taking_imaginary_part_out46),  // sfix15_En5
                                                 .Out47(taking_imaginary_part_out47),  // sfix15_En5
                                                 .Out48(taking_imaginary_part_out48),  // sfix15_En5
                                                 .Out49(taking_imaginary_part_out49),  // sfix15_En5
                                                 .Out50(taking_imaginary_part_out50)  // sfix15_En5
                                                 );

  parallel_serial u_parallel_serial (.clk(clk),
                                     .reset_x(reset_x),
                                     .enb(clk_enable),
                                     .In1(taking_imaginary_part_out1),  // sfix15_En5
                                     .In2(taking_imaginary_part_out2),  // sfix15_En5
                                     .In3(taking_imaginary_part_out3),  // sfix15_En5
                                     .In4(taking_imaginary_part_out4),  // sfix15_En5
                                     .In5(taking_imaginary_part_out5),  // sfix15_En5
                                     .In6(taking_imaginary_part_out6),  // sfix15_En5
                                     .In7(taking_imaginary_part_out7),  // sfix15_En5
                                     .In8(taking_imaginary_part_out8),  // sfix15_En5
                                     .In9(taking_imaginary_part_out9),  // sfix15_En5
                                     .In10(taking_imaginary_part_out10),  // sfix15_En5
                                     .In11(taking_imaginary_part_out11),  // sfix15_En5
                                     .In12(taking_imaginary_part_out12),  // sfix15_En5
                                     .In13(taking_imaginary_part_out13),  // sfix15_En5
                                     .In14(taking_imaginary_part_out14),  // sfix15_En5
                                     .In15(taking_imaginary_part_out15),  // sfix15_En5
                                     .In16(taking_imaginary_part_out16),  // sfix15_En5
                                     .In17(taking_imaginary_part_out17),  // sfix15_En5
                                     .In18(taking_imaginary_part_out18),  // sfix15_En5
                                     .In19(taking_imaginary_part_out19),  // sfix15_En5
                                     .In20(taking_imaginary_part_out20),  // sfix15_En5
                                     .In21(taking_imaginary_part_out21),  // sfix15_En5
                                     .In22(taking_imaginary_part_out22),  // sfix15_En5
                                     .In23(taking_imaginary_part_out23),  // sfix15_En5
                                     .In24(taking_imaginary_part_out24),  // sfix15_En5
                                     .In25(taking_imaginary_part_out25),  // sfix15_En5
                                     .In26(taking_imaginary_part_out26),  // sfix15_En5
                                     .In27(taking_imaginary_part_out27),  // sfix15_En5
                                     .In28(taking_imaginary_part_out28),  // sfix15_En5
                                     .In29(taking_imaginary_part_out29),  // sfix15_En5
                                     .In30(taking_imaginary_part_out30),  // sfix15_En5
                                     .In31(taking_imaginary_part_out31),  // sfix15_En5
                                     .In32(taking_imaginary_part_out32),  // sfix15_En5
                                     .In33(taking_imaginary_part_out33),  // sfix15_En5
                                     .In34(taking_imaginary_part_out34),  // sfix15_En5
                                     .In35(taking_imaginary_part_out35),  // sfix15_En5
                                     .In36(taking_imaginary_part_out36),  // sfix15_En5
                                     .In37(taking_imaginary_part_out37),  // sfix15_En5
                                     .In38(taking_imaginary_part_out38),  // sfix15_En5
                                     .In39(taking_imaginary_part_out39),  // sfix15_En5
                                     .In40(taking_imaginary_part_out40),  // sfix15_En5
                                     .In41(taking_imaginary_part_out41),  // sfix15_En5
                                     .In42(taking_imaginary_part_out42),  // sfix15_En5
                                     .In43(taking_imaginary_part_out43),  // sfix15_En5
                                     .In44(taking_imaginary_part_out44),  // sfix15_En5
                                     .In45(taking_imaginary_part_out45),  // sfix15_En5
                                     .In46(taking_imaginary_part_out46),  // sfix15_En5
                                     .In47(taking_imaginary_part_out47),  // sfix15_En5
                                     .In48(taking_imaginary_part_out48),  // sfix15_En5
                                     .In49(taking_imaginary_part_out49),  // sfix15_En5
                                     .In50(taking_imaginary_part_out50),  // sfix15_En5
                                     .In51(Counter_Limited4_out1),  // uint8
                                     .Out2(parallel_serial_out1)  // sfix15_En5
                                     );

  assign out1 = parallel_serial_out1;

  assign ce_out = clk_enable;

endmodule  // FDHT

