// -------------------------------------------------------------
// 
// File Name: C:\Users\Carlos Cajas\Desktop\henkindama2\newhope_cambios\Save_data_G.v
// Created: 2020-12-20 13:10:02
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Save_data_G
// Source Path: newhope_cambios/FDHT/DFT/Save_data_G
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Save_data_G
          (clk,
           reset_x,
           enb,
           din,
           din1,
           din2,
           din3,
           din4,
           din5,
           din6,
           din7,
           din8,
           din9,
           din10,
           din11,
           din12,
           din13,
           din14,
           din15,
           din16,
           din17,
           In19,
           din18,
           din19,
           real_G_0_0,
           dout1,
           real_G_1_0,
           dout3,
           real_G_2_0,
           dout5,
           real_G_3_0,
           dout7,
           real_G_4_0,
           dout9,
           real_G_0_1,
           dout11,
           real_G_1_1,
           dout13,
           real_G_2_1,
           dout15,
           real_G_3_1,
           dout17,
           real_G_4_1,
           dout19,
           real_G_0_2,
           dout21,
           real_G_1_2,
           dout23,
           real_G_2_2,
           dout25,
           real_G_3_2,
           dout27,
           real_G_4_2,
           dout29,
           real_G_0_3,
           dout31,
           real_G_1_3,
           dout33,
           real_G_2_3,
           dout35,
           real_G_3_3,
           dout37,
           real_G_4_3,
           dout39,
           real_G_0_4,
           dout41,
           real_G_1_4,
           dout43,
           real_G_2_4,
           dout45,
           real_G_3_4,
           dout47,
           real_G_4_4,
           dout49,
           real_G_0_5,
           dout51,
           real_G_1_5,
           dout53,
           real_G_2_5,
           dout55,
           real_G_3_5,
           dout57,
           real_G_4_5,
           dout59,
           real_G_0_6,
           dout61,
           real_G_1_6,
           dout63,
           real_G_2_6,
           dout65,
           real_G_3_6,
           dout67,
           real_G_4_6,
           dout69,
           real_G_0_7,
           dout71,
           real_G_1_7,
           dout73,
           real_G_2_7,
           dout75,
           real_G_3_7,
           dout77,
           real_G_4_7,
           dout79,
           real_G_0_8,
           dout81,
           real_G_1_8,
           dout83,
           real_G_2_8,
           dout85,
           real_G_3_8,
           dout87,
           real_G_4_8,
           dout89,
           real_G_0_9,
           dout91,
           real_G_1_9,
           dout93,
           real_G_2_9,
           dout95,
           real_G_3_9,
           dout97,
           real_G_4_9,
           dout99);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [36:0] din;  // sfix37_En22
  input   signed [36:0] din1;  // sfix37_En22
  input   signed [36:0] din2;  // sfix37_En22
  input   signed [36:0] din3;  // sfix37_En22
  input   signed [36:0] din4;  // sfix37_En22
  input   signed [36:0] din5;  // sfix37_En22
  input   signed [36:0] din6;  // sfix37_En22
  input   signed [36:0] din7;  // sfix37_En22
  input   signed [36:0] din8;  // sfix37_En22
  input   signed [36:0] din9;  // sfix37_En22
  input   signed [36:0] din10;  // sfix37_En22
  input   signed [36:0] din11;  // sfix37_En22
  input   signed [36:0] din12;  // sfix37_En22
  input   signed [36:0] din13;  // sfix37_En22
  input   signed [36:0] din14;  // sfix37_En22
  input   signed [36:0] din15;  // sfix37_En22
  input   signed [36:0] din16;  // sfix37_En22
  input   signed [36:0] din17;  // sfix37_En22
  input   [7:0] In19;  // uint8
  input   signed [36:0] din18;  // sfix37_En22
  input   signed [36:0] din19;  // sfix37_En22
  output  signed [36:0] real_G_0_0;  // sfix37_En22
  output  signed [36:0] dout1;  // sfix37_En22
  output  signed [36:0] real_G_1_0;  // sfix37_En22
  output  signed [36:0] dout3;  // sfix37_En22
  output  signed [36:0] real_G_2_0;  // sfix37_En22
  output  signed [36:0] dout5;  // sfix37_En22
  output  signed [36:0] real_G_3_0;  // sfix37_En22
  output  signed [36:0] dout7;  // sfix37_En22
  output  signed [36:0] real_G_4_0;  // sfix37_En22
  output  signed [36:0] dout9;  // sfix37_En22
  output  signed [36:0] real_G_0_1;  // sfix37_En22
  output  signed [36:0] dout11;  // sfix37_En22
  output  signed [36:0] real_G_1_1;  // sfix37_En22
  output  signed [36:0] dout13;  // sfix37_En22
  output  signed [36:0] real_G_2_1;  // sfix37_En22
  output  signed [36:0] dout15;  // sfix37_En22
  output  signed [36:0] real_G_3_1;  // sfix37_En22
  output  signed [36:0] dout17;  // sfix37_En22
  output  signed [36:0] real_G_4_1;  // sfix37_En22
  output  signed [36:0] dout19;  // sfix37_En22
  output  signed [36:0] real_G_0_2;  // sfix37_En22
  output  signed [36:0] dout21;  // sfix37_En22
  output  signed [36:0] real_G_1_2;  // sfix37_En22
  output  signed [36:0] dout23;  // sfix37_En22
  output  signed [36:0] real_G_2_2;  // sfix37_En22
  output  signed [36:0] dout25;  // sfix37_En22
  output  signed [36:0] real_G_3_2;  // sfix37_En22
  output  signed [36:0] dout27;  // sfix37_En22
  output  signed [36:0] real_G_4_2;  // sfix37_En22
  output  signed [36:0] dout29;  // sfix37_En22
  output  signed [36:0] real_G_0_3;  // sfix37_En22
  output  signed [36:0] dout31;  // sfix37_En22
  output  signed [36:0] real_G_1_3;  // sfix37_En22
  output  signed [36:0] dout33;  // sfix37_En22
  output  signed [36:0] real_G_2_3;  // sfix37_En22
  output  signed [36:0] dout35;  // sfix37_En22
  output  signed [36:0] real_G_3_3;  // sfix37_En22
  output  signed [36:0] dout37;  // sfix37_En22
  output  signed [36:0] real_G_4_3;  // sfix37_En22
  output  signed [36:0] dout39;  // sfix37_En22
  output  signed [36:0] real_G_0_4;  // sfix37_En22
  output  signed [36:0] dout41;  // sfix37_En22
  output  signed [36:0] real_G_1_4;  // sfix37_En22
  output  signed [36:0] dout43;  // sfix37_En22
  output  signed [36:0] real_G_2_4;  // sfix37_En22
  output  signed [36:0] dout45;  // sfix37_En22
  output  signed [36:0] real_G_3_4;  // sfix37_En22
  output  signed [36:0] dout47;  // sfix37_En22
  output  signed [36:0] real_G_4_4;  // sfix37_En22
  output  signed [36:0] dout49;  // sfix37_En22
  output  signed [36:0] real_G_0_5;  // sfix37_En22
  output  signed [36:0] dout51;  // sfix37_En22
  output  signed [36:0] real_G_1_5;  // sfix37_En22
  output  signed [36:0] dout53;  // sfix37_En22
  output  signed [36:0] real_G_2_5;  // sfix37_En22
  output  signed [36:0] dout55;  // sfix37_En22
  output  signed [36:0] real_G_3_5;  // sfix37_En22
  output  signed [36:0] dout57;  // sfix37_En22
  output  signed [36:0] real_G_4_5;  // sfix37_En22
  output  signed [36:0] dout59;  // sfix37_En22
  output  signed [36:0] real_G_0_6;  // sfix37_En22
  output  signed [36:0] dout61;  // sfix37_En22
  output  signed [36:0] real_G_1_6;  // sfix37_En22
  output  signed [36:0] dout63;  // sfix37_En22
  output  signed [36:0] real_G_2_6;  // sfix37_En22
  output  signed [36:0] dout65;  // sfix37_En22
  output  signed [36:0] real_G_3_6;  // sfix37_En22
  output  signed [36:0] dout67;  // sfix37_En22
  output  signed [36:0] real_G_4_6;  // sfix37_En22
  output  signed [36:0] dout69;  // sfix37_En22
  output  signed [36:0] real_G_0_7;  // sfix37_En22
  output  signed [36:0] dout71;  // sfix37_En22
  output  signed [36:0] real_G_1_7;  // sfix37_En22
  output  signed [36:0] dout73;  // sfix37_En22
  output  signed [36:0] real_G_2_7;  // sfix37_En22
  output  signed [36:0] dout75;  // sfix37_En22
  output  signed [36:0] real_G_3_7;  // sfix37_En22
  output  signed [36:0] dout77;  // sfix37_En22
  output  signed [36:0] real_G_4_7;  // sfix37_En22
  output  signed [36:0] dout79;  // sfix37_En22
  output  signed [36:0] real_G_0_8;  // sfix37_En22
  output  signed [36:0] dout81;  // sfix37_En22
  output  signed [36:0] real_G_1_8;  // sfix37_En22
  output  signed [36:0] dout83;  // sfix37_En22
  output  signed [36:0] real_G_2_8;  // sfix37_En22
  output  signed [36:0] dout85;  // sfix37_En22
  output  signed [36:0] real_G_3_8;  // sfix37_En22
  output  signed [36:0] dout87;  // sfix37_En22
  output  signed [36:0] real_G_4_8;  // sfix37_En22
  output  signed [36:0] dout89;  // sfix37_En22
  output  signed [36:0] real_G_0_9;  // sfix37_En22
  output  signed [36:0] dout91;  // sfix37_En22
  output  signed [36:0] real_G_1_9;  // sfix37_En22
  output  signed [36:0] dout93;  // sfix37_En22
  output  signed [36:0] real_G_2_9;  // sfix37_En22
  output  signed [36:0] dout95;  // sfix37_En22
  output  signed [36:0] real_G_3_9;  // sfix37_En22
  output  signed [36:0] dout97;  // sfix37_En22
  output  signed [36:0] real_G_4_9;  // sfix37_En22
  output  signed [36:0] dout99;  // sfix37_En22


  wire signed [36:0] save_values_real_G_x_0_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_0_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_0_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_0_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_0_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_0_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_0_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_0_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_0_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_0_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_1_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_1_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_1_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_1_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_1_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_1_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_1_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_1_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_1_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_1_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_2_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_2_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_2_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_2_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_2_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_2_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_2_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_2_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_2_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_2_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_3_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_3_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_3_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_3_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_3_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_3_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_3_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_3_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_3_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_3_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_4_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_4_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_4_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_4_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_4_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_4_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_4_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_4_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_4_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_4_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_5_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_5_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_5_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_5_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_5_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_5_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_5_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_5_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_5_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_5_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_6_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_6_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_6_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_6_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_6_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_6_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_6_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_6_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_6_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_6_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_7_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_7_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_7_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_7_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_7_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_7_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_7_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_7_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_7_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_7_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_8_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_8_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_8_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_8_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_8_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_8_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_8_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_8_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_8_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_8_out5;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_9_out1;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_9_out2;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_9_out3;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_9_out4;  // sfix37_En22
  wire signed [36:0] save_values_real_G_x_9_out5;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_9_out1;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_9_out2;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_9_out3;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_9_out4;  // sfix37_En22
  wire signed [36:0] save_values_im_G_x_9_out5;  // sfix37_En22


  save_values_real_G_x_0 u_save_values_real_G_x_0 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_0_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_0_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_0_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_0_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_0_out5)  // sfix37_En22
                                                   );

  assign real_G_0_0 = save_values_real_G_x_0_out1;

  save_values_im_G_x_0 u_save_values_im_G_x_0 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din1),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_0_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_0_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_0_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_0_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_0_out5)  // sfix37_En22
                                               );

  assign dout1 = save_values_im_G_x_0_out1;

  assign real_G_1_0 = save_values_real_G_x_0_out2;

  assign dout3 = save_values_im_G_x_0_out2;

  assign real_G_2_0 = save_values_real_G_x_0_out3;

  assign dout5 = save_values_im_G_x_0_out3;

  assign real_G_3_0 = save_values_real_G_x_0_out4;

  assign dout7 = save_values_im_G_x_0_out4;

  assign real_G_4_0 = save_values_real_G_x_0_out5;

  assign dout9 = save_values_im_G_x_0_out5;

  save_values_real_G_x_1 u_save_values_real_G_x_1 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din2),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_1_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_1_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_1_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_1_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_1_out5)  // sfix37_En22
                                                   );

  assign real_G_0_1 = save_values_real_G_x_1_out1;

  save_values_im_G_x_1 u_save_values_im_G_x_1 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din3),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_1_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_1_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_1_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_1_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_1_out5)  // sfix37_En22
                                               );

  assign dout11 = save_values_im_G_x_1_out1;

  assign real_G_1_1 = save_values_real_G_x_1_out2;

  assign dout13 = save_values_im_G_x_1_out2;

  assign real_G_2_1 = save_values_real_G_x_1_out3;

  assign dout15 = save_values_im_G_x_1_out3;

  assign real_G_3_1 = save_values_real_G_x_1_out4;

  assign dout17 = save_values_im_G_x_1_out4;

  assign real_G_4_1 = save_values_real_G_x_1_out5;

  assign dout19 = save_values_im_G_x_1_out5;

  save_values_real_G_x_2 u_save_values_real_G_x_2 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din4),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_2_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_2_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_2_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_2_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_2_out5)  // sfix37_En22
                                                   );

  assign real_G_0_2 = save_values_real_G_x_2_out1;

  save_values_im_G_x_2 u_save_values_im_G_x_2 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din5),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_2_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_2_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_2_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_2_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_2_out5)  // sfix37_En22
                                               );

  assign dout21 = save_values_im_G_x_2_out1;

  assign real_G_1_2 = save_values_real_G_x_2_out2;

  assign dout23 = save_values_im_G_x_2_out2;

  assign real_G_2_2 = save_values_real_G_x_2_out3;

  assign dout25 = save_values_im_G_x_2_out3;

  assign real_G_3_2 = save_values_real_G_x_2_out4;

  assign dout27 = save_values_im_G_x_2_out4;

  assign real_G_4_2 = save_values_real_G_x_2_out5;

  assign dout29 = save_values_im_G_x_2_out5;

  save_values_real_G_x_3 u_save_values_real_G_x_3 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din6),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_3_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_3_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_3_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_3_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_3_out5)  // sfix37_En22
                                                   );

  assign real_G_0_3 = save_values_real_G_x_3_out1;

  save_values_im_G_x_3 u_save_values_im_G_x_3 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din7),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_3_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_3_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_3_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_3_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_3_out5)  // sfix37_En22
                                               );

  assign dout31 = save_values_im_G_x_3_out1;

  assign real_G_1_3 = save_values_real_G_x_3_out2;

  assign dout33 = save_values_im_G_x_3_out2;

  assign real_G_2_3 = save_values_real_G_x_3_out3;

  assign dout35 = save_values_im_G_x_3_out3;

  assign real_G_3_3 = save_values_real_G_x_3_out4;

  assign dout37 = save_values_im_G_x_3_out4;

  assign real_G_4_3 = save_values_real_G_x_3_out5;

  assign dout39 = save_values_im_G_x_3_out5;

  save_values_real_G_x_4 u_save_values_real_G_x_4 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din8),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_4_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_4_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_4_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_4_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_4_out5)  // sfix37_En22
                                                   );

  assign real_G_0_4 = save_values_real_G_x_4_out1;

  save_values_im_G_x_4 u_save_values_im_G_x_4 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din9),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_4_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_4_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_4_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_4_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_4_out5)  // sfix37_En22
                                               );

  assign dout41 = save_values_im_G_x_4_out1;

  assign real_G_1_4 = save_values_real_G_x_4_out2;

  assign dout43 = save_values_im_G_x_4_out2;

  assign real_G_2_4 = save_values_real_G_x_4_out3;

  assign dout45 = save_values_im_G_x_4_out3;

  assign real_G_3_4 = save_values_real_G_x_4_out4;

  assign dout47 = save_values_im_G_x_4_out4;

  assign real_G_4_4 = save_values_real_G_x_4_out5;

  assign dout49 = save_values_im_G_x_4_out5;

  save_values_real_G_x_5 u_save_values_real_G_x_5 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din10),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_5_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_5_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_5_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_5_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_5_out5)  // sfix37_En22
                                                   );

  assign real_G_0_5 = save_values_real_G_x_5_out1;

  save_values_im_G_x_5 u_save_values_im_G_x_5 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din11),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_5_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_5_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_5_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_5_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_5_out5)  // sfix37_En22
                                               );

  assign dout51 = save_values_im_G_x_5_out1;

  assign real_G_1_5 = save_values_real_G_x_5_out2;

  assign dout53 = save_values_im_G_x_5_out2;

  assign real_G_2_5 = save_values_real_G_x_5_out3;

  assign dout55 = save_values_im_G_x_5_out3;

  assign real_G_3_5 = save_values_real_G_x_5_out4;

  assign dout57 = save_values_im_G_x_5_out4;

  assign real_G_4_5 = save_values_real_G_x_5_out5;

  assign dout59 = save_values_im_G_x_5_out5;

  save_values_real_G_x_6 u_save_values_real_G_x_6 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din12),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_6_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_6_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_6_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_6_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_6_out5)  // sfix37_En22
                                                   );

  assign real_G_0_6 = save_values_real_G_x_6_out1;

  save_values_im_G_x_6 u_save_values_im_G_x_6 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din13),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_6_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_6_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_6_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_6_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_6_out5)  // sfix37_En22
                                               );

  assign dout61 = save_values_im_G_x_6_out1;

  assign real_G_1_6 = save_values_real_G_x_6_out2;

  assign dout63 = save_values_im_G_x_6_out2;

  assign real_G_2_6 = save_values_real_G_x_6_out3;

  assign dout65 = save_values_im_G_x_6_out3;

  assign real_G_3_6 = save_values_real_G_x_6_out4;

  assign dout67 = save_values_im_G_x_6_out4;

  assign real_G_4_6 = save_values_real_G_x_6_out5;

  assign dout69 = save_values_im_G_x_6_out5;

  save_values_real_G_x_7 u_save_values_real_G_x_7 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din14),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_7_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_7_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_7_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_7_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_7_out5)  // sfix37_En22
                                                   );

  assign real_G_0_7 = save_values_real_G_x_7_out1;

  save_values_im_G_x_7 u_save_values_im_G_x_7 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din15),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_7_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_7_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_7_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_7_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_7_out5)  // sfix37_En22
                                               );

  assign dout71 = save_values_im_G_x_7_out1;

  assign real_G_1_7 = save_values_real_G_x_7_out2;

  assign dout73 = save_values_im_G_x_7_out2;

  assign real_G_2_7 = save_values_real_G_x_7_out3;

  assign dout75 = save_values_im_G_x_7_out3;

  assign real_G_3_7 = save_values_real_G_x_7_out4;

  assign dout77 = save_values_im_G_x_7_out4;

  assign real_G_4_7 = save_values_real_G_x_7_out5;

  assign dout79 = save_values_im_G_x_7_out5;

  save_values_real_G_x_8 u_save_values_real_G_x_8 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din16),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_8_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_8_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_8_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_8_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_8_out5)  // sfix37_En22
                                                   );

  assign real_G_0_8 = save_values_real_G_x_8_out1;

  save_values_im_G_x_8 u_save_values_im_G_x_8 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din17),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_8_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_8_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_8_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_8_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_8_out5)  // sfix37_En22
                                               );

  assign dout81 = save_values_im_G_x_8_out1;

  assign real_G_1_8 = save_values_real_G_x_8_out2;

  assign dout83 = save_values_im_G_x_8_out2;

  assign real_G_2_8 = save_values_real_G_x_8_out3;

  assign dout85 = save_values_im_G_x_8_out3;

  assign real_G_3_8 = save_values_real_G_x_8_out4;

  assign dout87 = save_values_im_G_x_8_out4;

  assign real_G_4_8 = save_values_real_G_x_8_out5;

  assign dout89 = save_values_im_G_x_8_out5;

  save_values_real_G_x_9 u_save_values_real_G_x_9 (.clk(clk),
                                                   .reset_x(reset_x),
                                                   .enb(enb),
                                                   .din(din18),  // sfix37_En22
                                                   .In2(In19),  // uint8
                                                   .dout(save_values_real_G_x_9_out1),  // sfix37_En22
                                                   .dout1(save_values_real_G_x_9_out2),  // sfix37_En22
                                                   .dout2(save_values_real_G_x_9_out3),  // sfix37_En22
                                                   .dout3(save_values_real_G_x_9_out4),  // sfix37_En22
                                                   .dout4(save_values_real_G_x_9_out5)  // sfix37_En22
                                                   );

  assign real_G_0_9 = save_values_real_G_x_9_out1;

  save_values_im_G_x_9 u_save_values_im_G_x_9 (.clk(clk),
                                               .reset_x(reset_x),
                                               .enb(enb),
                                               .din(din19),  // sfix37_En22
                                               .In2(In19),  // uint8
                                               .dout(save_values_im_G_x_9_out1),  // sfix37_En22
                                               .dout1(save_values_im_G_x_9_out2),  // sfix37_En22
                                               .dout2(save_values_im_G_x_9_out3),  // sfix37_En22
                                               .dout3(save_values_im_G_x_9_out4),  // sfix37_En22
                                               .dout4(save_values_im_G_x_9_out5)  // sfix37_En22
                                               );

  assign dout91 = save_values_im_G_x_9_out1;

  assign real_G_1_9 = save_values_real_G_x_9_out2;

  assign dout93 = save_values_im_G_x_9_out2;

  assign real_G_2_9 = save_values_real_G_x_9_out3;

  assign dout95 = save_values_im_G_x_9_out3;

  assign real_G_3_9 = save_values_real_G_x_9_out4;

  assign dout97 = save_values_im_G_x_9_out4;

  assign real_G_4_9 = save_values_real_G_x_9_out5;

  assign dout99 = save_values_im_G_x_9_out5;

endmodule  // Save_data_G

